### PR TITLE
Stat Pane View Improvements

### PR DESCRIPTION
**Pull request by Ebag333**
We're at the point now where this is mostly functional, but could use some help with the formatting as I'm absolutely garbage with wxPython.

Plenty left to do.
- [x] Convert Resistances to the minimal version.
- [x] Convert Recharge Rates to the minimal version.
- [x] Finish converting the Full into Minimal versions (mostly format cleanup).
- [ ] Break out drones into their own separate pane.
- [ ] Break out fighters into their own separate pane.
- [ ] Break out the misc stats some? (Separate Sensor pane?)
- [x] Move "Requires Restart" line onto it's own (so it doesn't overlap the Crest one when selected)
- [ ] Icon for the Preferences window.
- [ ] Tooltip improvements on the Panes (as long as we're in there...)

http://puu.sh/qjx59/1f96e21026.png

### CODE REVIEW

**Comment by Ebag333** [comment]
Paging @blitzmann 

So I think it's really close to being ready to be pushed out.  But I need a bit of help here....

First off, what it looks like.

Full/Default:
https://puu.sh/r4MWL/185e6fa066.png

Minimal:
https://puu.sh/r4NXJ/799bc1e3d3.png

(None not show as there's literally nothing to see. :D )


Okay, so what's left?

Maybe clean up the formatting/sizing/placement?  I'm terrible with wxPython.....

Big thing is to set the buttons that I added to pop open the context menu for Damage Profile and Resist Profile.

Pick a new preferences icon.

Want to assist with these? :)

**Comment by Ebag333** [comment]
Drone pane added!

Full:
https://puu.sh/rjl29/2698c9af4f.png

Minimal:
https://puu.sh/rjljE/3371c69150.png


Minimal is only a bit longer than the existing version.  _But_ with the extra ability to completely hide views you don't care about, I think this is a non-issue......

**Comment by IndictionEve** [comment]
totally like the idea of switching between different levels of information.
IMHO separate panel for different types of information would increase the usability and visibility a lot.
Currently the "Targeting and Misc" panel mix a lot of different information and makes it more difficult to read then necessary.

**Comment by Ebag333** [comment]
Ignore all the commit spam.  Just a rebase.

**Comment by Ebag333** [comment]
@blitzmann since I folded the actual preference window modifications into #868 half of this PR is no longer valid.

Question on the remaining half.

Would you prefer a single PR for all the new panes, or would you prefer a PR for each pane so we can hold a committee meeting and discuss in minutia if the text should be moved 2 pixels to the left or 3 to the right?  I'm good with either. :D 

Once you decide, I can create a new PR (either just one big one, or a couple smaller ones) and close this one.

**Comment by blitzmann** [comment]
Lets simply hold off on it for now until we actually figure out what we're going to be doing with this. I'm still not sold or 100% on board with it (or at least some of it). I need to sit down and go over it again since it's been a couple months since I last looked at it. :)

**Comment by Ebag333** [comment]
I know you aren't, and I know some are a bigger change than others.

I did _try_ very hard to leave the "Full" panes alone as much as possible, and it defaults to them.  Really the one that did change was breaking the drone stuff into it's own pane.

I know you're not a fan of the way that the minimal ones look, but remember that there are a _lot_ of EFT users who are displaced right now, and who don't like Pyfa because it's `too GUI` or `too cluttery` (basically `not EFT enough`).  I'm not personally a huge fan of the EFT design (I think it's a horrible UI for the stats layout, TBH), but as long as _I'm_ not forced to use it, I don't see any reason not to give users a Pyfa lite, if it makes them happier.

I've actually ran screenshots by a few users on Tweetfleet Slack who use EFT and don't like Pyfa's GUI.  Both of them approved of the changes, so to me that's progress in the right direction. :)

**Comment by blitzmann** [comment]
I'm not opposed to "minimal" versions, as stated before. Here are my concerns (as I remember them):

* Drone panel was way too big for what it is. It shouldn't take up more space the the resource pane, that's just ridiculous. I'm not sold yet on even separating it out into it's own pane, but I can see it happening. But we need to be smart about how we display the information.
* I am concerned about also splitting out Firepower / Mining / (eventual) Remote pane into their own separate things. There is very little reason to show these all at the same time considering they all deal with high-slot modules and certain playstyle of the fit. A mining fit is not going to primarily produce firepower, and a DPS fit is not going to primarily produce logistics. I want to look more into how to properly handle stat pane switching based on context (a feature EFT has) and give users the ability to switch between the panes (in a less gimpy way). The current implementation of firepower pane switching on the button was always meant as a stop gap until we find a way to fix the stats pane to support real hiding / showing. When I was actually playing EVE, this was one of the things that I got feedback on, and many of the folks in my circle didn't want 2-3 panes of irrelevant information to the current fit and agreed that toggling between them would be best.

That being said, please hold off on the PRs until I have a change to actually look at these things again. I just don't want to get into a situation where all this work is done and awaiting review, and we haven't even discussed basic functional and design goals, and having to throw out the work. If you want, feel free to keep branches going on your repo, but I do not want a PR overload happening. Still trying to go through everything that's out there lol

**Comment by Ebag333** [comment]
>Drone panel was way too big for what it is. It shouldn't take up more space the the resource pane, that's just ridiculous. I'm not sold yet on even separating it out into it's own pane, but I can see it happening. But we need to be smart about how we display the information.

It was a first pass.  It could easily be tightened up.  You know I'm bad at wxPython layout, so I was rather happy with the way it turned out given that it was a new format design from scratch. :)

>I want to look more into how to properly handle stat pane switching based on context (a feature EFT has) and give users the ability to switch between the panes (in a less gimpy way).

It should be split out because it's slightly frustrating to miners, who will usually have combat drones, so they have to toggle back and forth to see the two numbers.  It's also not good UI to have it hidden, I've talked with folks before who told me "I like Pyfa, but I stopped using it because it doesn't show mining numbers."  It's like the resists on the firepower/tank pane, hidden behind a context menu so a lot of users don't know about it.

There's also times when you're building fits that don't have various aspects of the UI.  No combat drones, or no turrets/missiles, or no mining lasers.  I agree that the ideal scenario is to hide the panes somehow, but wxPython doesn't deal well with toggling between panes (the drone bay vs cargo bay gets stuck for me _all_ the time).

Hmmm, I actually have a thought about this..... I think we might be able to minimize (not hide) panes with 0 stats on them.  I'm going to go poke around and see if I can make it happen.

**Comment by blitzmann** [comment]
> It should be split out because it's slightly frustrating to miners, who will usually have combat drones, so they have to toggle back and forth to see the two numbers.

Hence why I'm not entirely opposed to splitting out drones. It really depends on how this looks.

> but wxPython doesn't deal well with toggling between panes (the drone bay vs cargo bay gets stuck for me all the time).

wxPython is a very powerful library if you know how to use it. These things can usually be solved with a bit of research and tinkering. Just because it's somewhat broken now doesn't mean it's unfixable. But it is indeed much more difficult than, say, html/css (hence my strong opinion on that)

>Hmmm, I actually have a thought about this..... I think we might be able to minimize (not hide) panes with 0 stats on them. I'm going to go poke around and see if I can make it happen.

I would still prefer them to hide completely, but this might be a decent solution in the interim. Take a look if you want.

> Part of the reason why I'm leaning toward 1 PR per pane, so we stay focused on on thing and don't get distracted.

I can get behind this.

> It's also not good UI to have it hidden, I've talked with folks before who told me "I like Pyfa, but I stopped using it because it doesn't show mining numbers." It's like the resists on the firepower/tank pane, hidden behind a context menu so a lot of users don't know about it.

Hence why I say there should be a better way to toggle between them. The context menus have always been a pain point, but what exactly are you gonna do about it? I envision having a small menu icon that, when clicked, spawns the menu for that pane.

Then again, how deep down the rabbit hole do we want to get here? pyfa in it's current iteration is EoL

**Comment by Ebag333** [comment]
>Then again, how deep down the rabbit hole do we want to get here? pyfa in it's current iteration is EoL

Judging by the rate of work on Pyfa-NG/Eos, EoL might be IGB or OGB levels of EoL.  In other words, around for another 4 or 5 years. :)

Adding/reworking the stats pane isn't a huge task, though.  I agree we shouldn't go to crazy lengths, but just adding some new optional versions, or moving things around is pretty simple.

**Comment by blitzmann** [comment]
> Judging by the rate of work on Pyfa-NG/Eos, EoL might be IGB or OGB levels of EoL. In other words, around for another 4 or 5 years. :)

Well, it's my intention to start getting things together for it early next year. I'll be done with my degree and have much more time to spend on it (hopefully!)

We'll see how things progress forward.

**Comment by blitzmann** [comment]
@Ebag333 I'm closing this PRs as half the functionality has been merged with the pref pane PRs.

As to the outstanding issues (new panels):

I am still of strong opinion that we should not go overboard with the amount of panels that we show, at least in the current codebase. With the addition of the Remote Reps panel, my pyfa window is now overlapped by my taskbar on my laptop (1377 is still a fairly popular resolution for laptop). I included it because I see it as a major improvement and information that we didn't have previously, whereas things like mining state are there, but togglable, and drone information is there (but scattered).

You may say "well they have the ability to toggle things on/off/minimal in preferences". That is true, but that requires a restart of pyfa, so not user friendly. So if a pvp player who normally doesn't mine and has that turned off wants to turn it on, they have to go to prefs, turn it on, and restart. They can also collapse it, but that is also not good user design (to start with all these panels only to have users be required to collapse them to possibly see lower panels).

Before any further work goes into this, I would like for us to research into how to dynamically hide / show panels based on their information (for example if all four RR stats are 0 or None, hide the panel completely. Same with mining states).

This would probably require a method on the stats pane, something like `isHidden()` which returns true if we hide. During recalc, we can reevaluate this. On recalc, we may have to de-register then re-register the panels to the parent (determining if they register could be a part of the `isHidden` method) and then `Layout()` or something. I don't think it will be a simple task, but being able to dynamically hide these things will be good in the long run, and is something that has been wanted for a while. It will also be much easier for me to OK a new drone panel, mining panel, eject from ship panel, what have you.

I'm going to make an issue on it to track progress. And if you want, I can look into this if you're not all that comfortable with wx. I have a couple ideas here and there about it.

**Pull request closed without merging**
