### PR TITLE
Statspanel/Option: total-price calculation

### PR DESCRIPTION
**Pull request by IndictionEve**
One thing I never felt comfortable with, was the calculation of the total price in the statspanel.
For me (as FC) drones and cargo are absolutely relevant for the total price.
When creating fittings for solo PVP, project-related implants are an issue.
All these different requirements are already covered by the structure of the source code.
I have now made these structures available to the user via options.
python_2019-03-17_10-52-47

In addition, I have extended the hints to provide extended price information discretely, even without using the options.

image
image

### CODE REVIEW

**Comment by DarkFenX** [comment]
@IndictionEve these options are already available via RMB menu on price panel, as far as i understand. In fact, I also enable cargo and drones into total price. We can set these two enabled as default.

**Comment by IndictionEve** [comment]
Oh my god, that's one of the hidden features of pyfa.
Never had the idea to use RMB on this panel.
We should think about some kind of indicator, where popup menus for panels are available. 

How should we handle this PR: 
- Implement as additional way to set the prices?
- Just keep the hints?
- Abandon it completely?

**Comment by blitzmann** [comment]
Yeah, I agree, it's not very visible. But I've never heard of a better suggestion on how to let the user know about it.

My opinion is we can keep the preference options as another way of setting which things are included. As for the tooltips, I'm not too sure if theres a use case for knowing the breakdown of cost by slot. Nor do I really thing we need a tooltip for the total as its displayed, since all that information is already displayed in the panel

What do you guys thin

**Comment by blitzmann** [comment]
Actually, I have thought about adding a sort of menu icon to panels that have context menus. But I've never looked into it.

**Comment by IndictionEve** [comment]
I am the kind of person who wants to know exactly what something is made of. 
and I love those statistics and analysis (Yeah, I know... ).
is this function useful? maybe not. 
is it a step backwards? i don't think so. 
is it interesting? for sure.

I was working on a new fleet doctrine the last few days. I found that the costs for the rigs and low slots would have made that fitting much more expensive then it worth.
Would I have recognized that without tooltip? Sure. 
But I always like it, when a tool delivers me information like that directly.
i don't want to push this. I just want you to understand my reasons. 
If you don't like it, I will gladly remove the tooltips. 😄

**Comment by DarkFenX** [comment]
As a theorycrafter myself, I disagree. When you determine effectveness of a doctrine, cost of modules in specific slot doesn't matter. Some ships have 1 module which is more expensive than the rest of fitting combined with a ship (e.g. armor keres with mutated warp disruptor) and it makes sense. What matters is:

- what kind of stats do you get from it
- how much money does it cost upfront
- maintenance cost (ammo, drugs, fuel)
- logistics cost (rigs which are lost during repackaging, some modules which you cannot move due to volume restrictions)
- maybe some other costs i've forgotten

The rest is "for fun" and I rather would not put it anywhere in pyfa.

However, your pull request raises important question about UI: the fact that you did not know about that menu (and I also did not until 2 months ago) shows that it can be improved. I will create seprate ticket for stats panel context menus / main menu / preferences later today.

**Comment by DarkFenX** [comment]
FYI when working on #1868 I decided to introduce set of options for metagroups buttons, and decided to move all market and price-related options there. To do that, I've grabbed commit from your branch. Also I enabled drones and cargo into total price as default.

As I still disagree with detailed popups, I will close this pull request now. "Total" price preferences will be merged into master with "market_metagroups" branch.

**Comment by IndictionEve** [comment]
@DarkFenX thank you very much. I'm fine with that. 
sorry for the late answer, but i was not able to have a look in here for a couple of days.

**Pull request closed without merging**
