### PR TITLE
Setup more standard setup.py

### PR DESCRIPTION
**Pull request by Ebag333**
The old setup was very...special.

This is moving back toward a more standardized setup, and one with proper requirements in it to make it easier to setup environments.

Need to confirm with @blitzmann  that this doesn't break the build process.

### CODE REVIEW

**Comment by blitzmann** [comment]
My question about this PR is: why? What are the benefits (besides the requirements file, which I'm okay with)?

I'm not going to merge changes to setup.py without there being a good reason. It was a bitch to get it to set up, and honestly is still a bitch to work with. This would break the build process, as now our `dist.py` script doesn't have the information it needs (which is imported via the setup script during release building). I don't think we ever discussed the current build process, have we? It seems you don't really understand how we use the current setup file (which is understandable because I almost definitely don't use it correctly lol).

pyfa utilizes it in two fashions:
1) Building binaries for Windows and OS X -- this only happens if required (see: upgrade to wxWidgets 3.0). Due to the pain of building the binaries, mostly because OS X is required to build the OS X binary, pyfa does not build them for each and every release. Instead, we generate the binaries when needed, strip out the source code files from the package that is generated, and then store the binaries in the `pyfa-skel` repository. The actual build process for release is done via the `scripts/dist.py` script, and it basically pulls the latest changes to `pyfa` repo and `pyfa-skel` repo, merges them, and zips up the result into a release file. It's a poor mans build process, but one that works fairly well. I can go into more detail about this if needed. :)
2) `dist.py` uses values in `setup.py` to select which directories are copied over to the final release packages.

The new setup.py proposed doesn't cover any other those cases, and I'm just curious as to what the new setup file does accomplish.

**Comment by blitzmann** [comment]
I should stress that the things that have been added (like requirements in `setup()`) I can get behind. However, completely obliterating the file is a no go ;)

**Comment by Ebag333** [comment]
>The new setup.py proposed doesn't cover any other those cases, and I'm just curious as to what the new setup file does accomplish.

The goal was to be able to get to a point where you build it like a "normal" Python package.  Or at least as normal as we can get.

I freely admit that I don't know nearly enough about python package building, but there's a number of things you mentioned (like handling building Mac vs Windows) that a standard `setup.py` _should_ be able to handle in a straight forward manner.

This isn't anywhere near complete, and it might all be screwed anyway because of wxPython.

>I should stress that the things that have been added (like requirements in setup()) I can get behind. However, completely obliterating the file is a no go ;)

I actually renamed the original to setup-old.py. :)

**Comment by blitzmann** [comment]
> The goal was to be able to get to a point where you build it like a "normal" Python package. Or at least as normal as we can get.

Trust me, this _is_ as normal as I could get it. Unfortunately, in order to build pyfa binaries from source, various things have to be in alignment and you need the divine grace of the gods to do it. Granted, I am not versed much in the ways of build processes either - I basically hacked at this until it worked and then stopped for fear of it breaking again. 

Out of sheer curiosity, I just tested building a Windows binary using `setup.py build`. Shockingly, it worked, with everything seemingly working fine, so I'm not sure why the changes? (no comment on OS X builds - i fucking despise doing them. It may or may not currently work)

>I actually renamed the original to setup-old.py. :)

I saw that. What I'm saying is that it still needs to be in set up.

**Comment by Ebag333** [comment]
>I saw that. What I'm saying is that it still needs to be in set up.

Mac/other you need to have a special build section with their instructions.  So yeah, that needs to be added, but the way I see to do it in the documentation isn't quite how it's been done.

Plus I don't have a Mac.  But I do have access to a few people who do......

**Comment by blitzmann** [comment]
@Ebag333, I'm going to close this pull request as I feel it's unnecessary at this time to fuck with setup.py.  I don't see the value of it. However, if you want to submit a PR for the requirements.txt and include that in the `setup()` function, feel free :)

**Pull request closed without merging**
