### PR TITLE
Add option to open fit in new tab

### PR DESCRIPTION
**Pull request by Will-W**
Just a quick usability update suggested by a corpmate.

Works from context menu and on middle click - like a web browser

### CODE REVIEW

**Comment by blitzmann** [comment]
I had thought middle click already worked. Nope, it was CTRL Click.

The only thing that I'm iffy on is this bit:

`wx.PostEvent(self.mainFrame, FitSelected(fitID=self.fitID, startup=2))`

The `startup` parameter really should only be used during startup, not during normal program execution. Normally I would recommended looking here:

https://github.com/pyfa-org/Pyfa/blob/master/gui/builtinViews/fittingView.py#L72

And trying to extract the middle click from the GetMouseState(), and then handling it there.

That being said, I've been meaning to look into how these events fundamentally work throughout pyfa and if they are named appropriately. The page handling is done in the FitSpawner class but, IMO, a lot of the things that it does should be handled via attributes on the events themselves (like open in new tab, etc).

I'll test this out tonight and merge ASAP. The review of the events will have to be done at a later date. :) Thanks for the contribution!

**Comment by Will-W** [comment]
It just felt like a better separation of concerns that the thing handling the click event made the distinction rather than thing spawning fits. An example of the issue is handling of paste: if I do it from the menu, it opens the new fit in the same tab. If I do it using ctrl+v, because ctrl happens to be down, you get a new tab.

Using a parameter called 'startup' is admittedly a bit hacky, but the naming could be changed and it given more meaningful IDs (e.g. NORMAL, NEW_TAB_NO_CALCULATE, NEW_TAB).

That said, it is of course your call and I did depart from the established convention. Happy to rework it if you want.

**Comment by blitzmann** [comment]
Nope, we're both in agreement with everything stated. It's not current convention, but in this case current convention is kinda hacky and I've been meaning to change it. No need for tweaking, this is fine as is as soon as I can test it. :)

**Comment by Ebag333** [comment]
Code looks good? Check.
Nice little QoL improvement? Check.
Passes Travis? Check.
Slightly hacky? Check.

Looks like a good pyfa PR to me. 😁

**Pull request merged**
