### PR TITLE
Catch scenario where Damage Profile and Target Resist names are missing

### PR DESCRIPTION
**Pull request by Ebag333**
See #949 for history.

Catches both null and empty names.  Sets name to `Unknown` if found.

### CODE REVIEW

**Comment by blitzmann** [comment]
This needs to be in a migration script, not one of our clean up scripts.

**Comment by Ebag333** [comment]
This isn't migrating data, and it's not fixing the DB issues.  It's just getting users back on their feet just like the other cleanup scripts.

**Comment by blitzmann** [comment]
> This isn't migrating data, and it's not fixing the DB issues. It's just getting users back on their feet just like the other cleanup scripts.

Which should happen in the migration script. I would rather have a migration script that fixes the database once and implements fixes on the database level to ensure it doesn't happen again than to have something the covers up the issue.

**Comment by Ebag333** [comment]
The migration script can call this function to run a repair on the database.  Either way, this code has to be written.  Where we put it and what we call it doesn't really matter, the process and end result is the same.  There's no reason a migration script can't import this, there's a reason why it's called `databaseRepair` and why it's very standalone (has minimal imports).

The only reason we're calling the function in `prefetch` is because we need to run it at some point before the database is in use, it could have easily been added as an extension of the migration scripts rather than a stand alone module.  If we use it in a migration script, then we can yank the reference to it from `prefetch`.

**Comment by blitzmann** [comment]
Okay, I can get behind that. 

> If we use it in a migration script, then we can yank the reference to it from prefetch.

Yes please, remove it from prefetch. I'll work on the migration maybe tonight :)

**Comment by Ebag333** [comment]
>I'll work on the migration maybe tonight :)

IMHO the DB issues are more pervasive than just a single field.  There isn't a unified design behind the tables, there's tons of stuff that's half implemented, and the DB restraints aren't really there for most things.

I'd like for us to sit down and figure out a way to fix all of these issues, and create a single migration script.  It's not any more complex to migrate _all_ the tables instead of just a single table, so I'd rather do it in one fell swoop than doing all the work for one at a time.

To me the DB corruption is a separate (if related) issue, and since they can be handled separately might as well, especially since a proper DB migration will take significant effort and adding a check for this corruption was copy/pasta and tweak a query.

Anyway, I removed the reference out of `prefetch`.

FYI (and you probably noticed this already) but I abstracted out the actual query execution.  I wasn't thrilled with encapsulating that much code in a try/catch, and the bigger issues is that you don't know which of the queries failed (since we usually have 2 or 3).  So now the error handling is more granular, and it spits out exactly which query it failed on.

**Comment by blitzmann** [comment]
> IMHO the DB issues are more pervasive than just a single field. There isn't a unified design behind the tables, there's tons of stuff that's half implemented, and the DB restraints aren't really there for most things.

Well, we can debate the structure of the database night and day. Fact remains that we're working off a codebase that was started 7-8 years ago, so yeah, it's gonna be funky. I've already identified a few things that will help corruption in the future (such as setting autoincrement for IDs), but I agree we should take a look and start adding more constraints where we need them, starting with the damage / target resist profiles. I am not a fan of doing a large batch of database changes at once though; I prefer to do these in iteration. Last thing I want is to fuck up a users database because one thing failed.

**Comment by Ebag333** [comment]
>Well, we can debate the structure of the database night and day. Fact remains that we're working off a codebase that was started 7-8 years ago, so yeah, it's gonna be funky.

I don't think either of us disagrees about the state of things.  Or that they should get fixed.  Or even generally on how to do it.

Just the difference between tearing off the duct tape all at once, or very slooooowly. :)

**Comment by blitzmann** [comment]
I changed it to a DELETE instead of an update. I don't know what multiples of the same name would do (if anything), and my thought it that users won't miss having it since they never had access to it in the first place. v0v

**Comment by Ebag333** [comment]
Multiple names SHOULD be fine, but I see your point. I just hate deleting user data.

**Pull request merged**
