### PR TITLE
Added commandline arguments to specify window title and path for savefiles

### PR DESCRIPTION
**Pull request by SpeedProg**
*  Settable Window Title using commandline arguments
  *  helps to distinguish between different instances
*  Settable savefile path using comandline arguments
  * allows for multiple instances to not mix the fittings/characters

I personally needed these changes because I use pyfa to check hundreds of fits a day, and having them mixed with my personal fits was a pain! (Deleting even more after that confirmation box was introduced)

### CODE REVIEW

**Comment by blitzmann** [comment]
> I personally needed these changes because I use pyfa to check hundreds of fits a day

Wait, what exactly are you doing that you need to check hundreds of fits per day? That's insane!

> (Deleting even more after that confirmation box was introduced)

Protip: Shift+click the delete to bypass the delete confirmation. =D

I'll take a look at this later on. Thanks!

**Comment by SpeedProg** [comment]
well I fc/fleetcomp for incursions.
I know a lot of fits how they should look like to meet our tanking requirements but ppl are good at making weird tank mod compositions. So yeah if I do that for some hours a day there are easily a few hundred fits in pyfa :D

**Comment by blitzmann** [comment]
Im intrigued. Why dont you just import the eft format and then delete it afterwards after checking? Do people supply you with their own database? 

Btw, took a quick look at the pull request, and it looks good. Ill test tonight and merge if no problems.

**Comment by SpeedProg** [comment]
takes up to much time to delete the fit after checking in I don't really have more then a few seconds when it is a busy time.
So I normally just copy to clipboard in eve, paste to pyfa look at the values and move on :D

**Comment by SpeedProg** [comment]
it might be that the command argument to unicode conversion of the title needs to happen in an other way to handle console specific (os specific) character sets.
I didn't know enough about python to do that :/

**Comment by MonfortB** [comment]
It's probably not much but wouldn't it be better to rename your variable ```savepath``` to something like ```customPath``` in order to avoid any confusion with the existing global variable ```savePath```.  
Having two variables in the same method with names different only because of one uppercase letter doesn't strike me as a good idea.

**Comment by SpeedProg** [comment]
xD might be a good idea to rename it to customSavePath yeah

**Pull request merged**
