### PR TITLE
Stop applying neut resistance twice

### PR DESCRIPTION
**Pull request by burnsypet**
Energy neut/nos resistance was being applied twice when a nos or
neut is projected onto a fit. I have removed the redundant resistance
application in energyneutralizerfalloff.py and also in
energynosferatufalloff.py as they are already being applied once in
eos.saveddata.fit.addDrain.

---

#1315 

Cap warfare resistance was being applied twice when a nos or neut was projected onto a fit, because it is applied in both the falloff effect and also in the addDrain function which is called by the falloff effect. Removed the resistance calculation from the falloff effect because it calls addDrain anyway.

### CODE REVIEW

**Comment by burnsypet** [comment]
@blitzmann looks like the Rifter test case is failing because the ship attributes have changed. I can whip up some amended test cases this week if you think it would add some value?

**Comment by blitzmann** [comment]
> @blitzmann looks like the Rifter test case is failing because the ship attributes have changed. I can whip up some amended test cases this week if you think it would add some value?

no need, I just removed the test yesterday. Those tests aren't properly mocked anyway, so anytime something changes in the database, there's the possibility that it fails. Unit testing shouldn't rely on info straight from the database, and thus pyfa needs to have properly mocked tests.

Will take a look at this PR now, sorry for the delay ;)

**Comment by blitzmann** [comment]
So, i'm thinking you were close, but that it's the other way around - we want to keep the ones in the effects, and get rid of the one in `addDrain()`.

The one in `addDrain()` is older code back when CCP only did resists against cap stuff. Now that they have resists against everything (remote reps, remote caps, etc), they moved over to a more robust system. To top it off, they had, at one point, two different systems for determining the resistance of a bonus - having the module have a `remoteResistanceID` that pointed to a attribute on the module determining how much to resist by, and then moving over to a resist that was on the effect itself. CCP at one time had both systems being utilized so we had to make sure both bases were covered, which might be one of the reasons why this is now a problem? See https://github.com/pyfa-org/Pyfa/issues/1139#issuecomment-298801620 for more details on this.

Gonna keep this PR open while I do some more investigating - will bring it in and make any modifications that I need, but hopefully it's simple keeping the effects the same and removing the resist stuff from `addDrain()`

**Comment by burnsypet** [comment]
That's pretty interesting, just felt a bit odd that the resistance was bundled in with the falloff effect. Although to be honest now that I look at it that falloff effect doesn't really seem to be doing much else.

**Comment by blitzmann** [comment]
>  just felt a bit odd that the resistance was bundled in with the falloff effect

TBH, a lot of eos feels odd because it's been the calc engine behind pyfa since it's inception lol. A lot of it is bolted on, including this, which is the only way that we have of passing in an effect that we can access in the calcs to determine resists for everything that has it. I'm just surprised that no one else has noticed the double resist bug until now... <_<

**Pull request merged**
