### PR TITLE
Apply proxy settings for requests library. Fixes #1465

### LINKED ISSUE #1465: Reimplement proxy support
pyfa has migrated over to using the `requests` package for all it's network calls. I haven't had time to research how to implement proxy support, so have disabled the code and removed controls from the GUI. Need to look into how to properly apply proxy information

### PR DESCRIPTION
**Pull request by minlexx**
I didn't test it yet (Pyfa crashes when trying to add a new character - Issue #1468 )
Coded according to documentation.
Will try to test in in WIndows later...

In attempt to fix #1465

### CODE REVIEW

**Comment by blitzmann** [comment]
Quick look at the code - it looks proper. Would like to test, but I don't really remember how to set up a proxy lol. Will have to research it a bit, IIRC it was kind of a hassle, had to be done on Linux with squid, etc...

**Comment by minlexx** [comment]
I tested in debug and can confirm that with this patch `requests` at least tries to connect through proxy. I don't have a proxy running right now, and it ends up with `HTTPSConnectionPool(host='api.eveonline.com', port=443): Max retries exceeded with url: /account/Characters.xml.aspx?keyID=xxxxxxx&vCode=Lo8ocdCw0a1zDO2ag...U9VuuBHo3p (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000238B5F1EF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))`

I'll try tomorrow to verify that it actually works through proxy and proxy authentication as well 😄

**Comment by blitzmann** [comment]
Thanks @minlexx, that would be a huge help :)

**Comment by minlexx** [comment]
So, a version `4.0.0b2 gtk3` of wxPython fixes crash in Linux, too, and I tested that proxy connection is indeed working.

I have a squid setup that requires login and password; so:
- when pyfa is configured to use proxy, but with no login/password set, I get this in squid logs:
```
1520322074.619      1 127.0.0.1 TCP_DENIED/407 3844 CONNECT api.eveonline.com:443 - HIER_NONE/- text/html
```
and pyfa reports proxy connection error
- when I additionally configure valid login and password: 
```
1520322174.919    277 127.0.0.1 TCP_TUNNEL/200 5332 CONNECT api.eveonline.com:443 minlexx HIER_DIRECT/87.237.34.208 -
1520322184.962    273 127.0.0.1 TCP_TUNNEL/200 5332 CONNECT api.eveonline.com:443 minlexx HIER_DIRECT/87.237.34.208 -
1520322185.428    296 127.0.0.1 TCP_TUNNEL/200 30367 CONNECT api.eveonline.com:443 minlexx HIER_DIRECT/87.237.34.208 -
1520322186.117    273 127.0.0.1 TCP_TUNNEL/200 10248 CONNECT api.eveonline.com:443 minlexx HIER_DIRECT/87.237.34.208 -
```
and pyfa reports `Successfully fetched Lexx Min's skills from EVE API.`

So yes, it is working, and proxy settings are saved correctly between restarts of Pyfa. Interesting thing is that `requests` prefers to use HTTPS proxy method CONNECT, SSL tunnel, not just plain HTTP. :thinking:

**Comment by blitzmann** [comment]
Thanks for the testing @minlexx! Will take a look soon and hopefully functionality into the branch

**Comment by blitzmann** [comment]
merged! Thanks!

**Pull request merged**
