### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by evrial**
Added Homebrew formula https://github.com/caskroom/homebrew-cask/commit/0ed8244441ec63b550d591b3f5b7430b6b7b53d4

### CODE REVIEW

**Comment by blitzmann** [comment]
Thanks for the PR. I don't have an issue with it, however... @thorr18 weren't you working on something similar? #515

I don't know much about it, so I'm going to have you guys discuss this for now. If nothing happens, I'll merge this sometime for v1.22 next monthish

**Comment by evrial** [comment]
That's funny, he wasn't aware of homebrew-cask and compiled from scratch. Anyway, my formula already published and works.

**Comment by blitzmann** [comment]
Curious, whats the update process like for this? Does it manually have to be update and submitted, or does it automatically check and download the latest release (I see the Release atom page in there)

**Comment by vitorgalvao** [comment]
Homebrew-cask maintainer here, replying [at the request](https://github.com/caskroom/homebrew-cask/pull/20943#issuecomment-216759065) of @evrial.

> Does it manually have to be update and submitted, or does it automatically check and download the latest release

A bit of both, kind of. It does need to be manually update and submitted, yes, but we have scripts to automatically check when the app itself is out of date (hence the atom release page) making the update process faster. That said, although said scripts work well, there are still some logistics of updating we’re working on, and currently they’re not run very regularly (that is the goal, eventually).

Updating is an extremely fast process, though. With a [minimum of setup](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md), submitting a new update becomes as easy as `cask-repair --cask-version {{new_version_here}} --blind-submit pyfa`. That will submit the updated cask to us.

After that, we’re pretty fast at merging new PRs, especially when they’re simply version bumps. Usually no more than a few hours, and many times no more than a few minutes.

**Comment by blitzmann** [comment]
Thanks for the clarification. I'm going to trust @evrial on this as I am not a mac guy. As long as it works. =)

**Pull request merged**
