### PR TITLE
Fix unread description

### PR DESCRIPTION
**Pull request by jeffy-g**
I often record descriptions in fit.

EVE client embeds description as "description" tag in exporting xml file,
Pyfa's import ignores this. (EFT is also true)

I think that explanation about fit should be kept,
I thought about adding source code so that pyfa can hold them.

However, in that process I found that the EVE client's xml export does not function properly under the English environment.

I have them and &lt;localized hint = "localized Name"&gt;Name&lt;/ localized&gt;
I intended to correspond, but may not be enough

Also, import a lot of fit data,
I also report that pyfa crashes when scrolling with ship view
(Import 1129 fit data, windows 7 64 bit intel core i 5 - 2500 k memory 16 G)

### CODE REVIEW

**Comment by Ebag333** [comment]
You've got a lot going on in this.  Can you explain a bit more?

Specifically, looking for more information on the following.

>However, in that process I found that the EVE client's xml export does not function properly under the English environment.

Can you go into detail on this? What is the issue you're seeing?

>I also report that pyfa crashes when scrolling with ship view

Haven't seen this.  Can you give an example where this can be replicated?

**Comment by jeffy-g** [comment]
Thanks for reply

The problem with export of EVE client
The xml file containing the localized item name points to incorrect

I'm sorry, but I have to go to bed now
Since detailed responses on your question will be done at a later date,
Please wait for a little while

**Comment by Ebag333** [comment]
No rush.  It looks like you have a lot of good fixes/improvements in here, just want to make sure I understand. :)

**Comment by jeffy-g** [comment]
night :-)

**Comment by blitzmann** [comment]
I have wanted to include description into notes field ever since that was added by one of our contributors. 

However, this seems like a very large change just to support description exports into pyfa's `notes` field. I'm aware you ran into an additional problems with localization, but I feel like that can be solved at much less overhead. Will have to take a look more closely. Seems interesting anyway :)

Could you maybe break down a list of the issues you were running into and your changes to solve those issues? It seems there are other things here besides support for localization and adding fit description to pyfa notes.

> I also report that pyfa crashes when scrolling with ship view

Yeah, it's because we open all those fits in the ship browser. A large list of ships would probably cause it to lag. Haven't tested this, but if that's the case we can probably limit it to show only the first 100 ships or so.

For reference, here's a XML export of a loki fit of mine:

```
<fitting name="4x web Loki-">
			<description value=""/>
			<shipType value="Loki"/>
			<hardware slot="hi slot 5" type="Auto Targeting System II"/>
			<hardware slot="low slot 1" type="Tracking Enhancer II"/>
			<hardware slot="low slot 0" type="Damage Control II"/>
			<hardware slot="hi slot 0" type="425mm AutoCannon II"/>
			<hardware slot="hi slot 1" type="425mm AutoCannon II"/>
			<hardware slot="hi slot 2" type="425mm AutoCannon II"/>
			<hardware slot="hi slot 3" type="425mm AutoCannon II"/>
			<hardware slot="hi slot 4" type="425mm AutoCannon II"/>
			<hardware slot="low slot 2" type="Republic Fleet Gyrostabilizer"/>
			<hardware slot="low slot 3" type="Republic Fleet Gyrostabilizer"/>
			<hardware slot="low slot 4" type="Republic Fleet Gyrostabilizer"/>
			<hardware slot="med slot 0" type="Federation Navy Stasis Webifier"/>
			<hardware slot="med slot 1" type="Federation Navy Stasis Webifier"/>
			<hardware slot="med slot 2" type="Federation Navy Stasis Webifier"/>
			<hardware slot="med slot 3" type="Federation Navy Stasis Webifier"/>
			<hardware qty="2" slot="drone bay" type="Garde II"/>
			<hardware slot="subsystem slot 2" type="Loki Defensive - Adaptive Shielding"/>
			<hardware slot="subsystem slot 0" type="Loki Electronics - Immobility Drivers"/>
			<hardware slot="subsystem slot 3" type="Loki Propulsion - Chassis Optimization"/>
			<hardware slot="subsystem slot 4" type="Loki Offensive - Projectile Scoping Array"/>
			<hardware slot="subsystem slot 1" type="Loki Engineering - Supplemental Coolant Injector"/>
			<hardware slot="rig slot 2" type="Medium Anti-Explosive Screen Reinforcer II"/>
			<hardware slot="rig slot 0" type="Medium Anti-Kinetic Screen Reinforcer II"/>
			<hardware slot="rig slot 1" type="Medium Core Defense Field Extender II"/>
			<hardware slot="med slot 4" type="Republic Fleet Large Shield Extender"/>
		</fitting>
```

Here's the same loki fit when client is set to russian:

```
<fitting name="4x web Loki-">
			<description value=""/>
			<shipType value="&lt;localized hint=&quot;Loki&quot;&gt;Loki*&lt;/localized&gt;"/>
			<hardware slot="hi slot 5" type="&lt;localized hint=&quot;Auto Targeting System II&quot;&gt;Auto Targeting System II*&lt;/localized&gt;"/>
			<hardware slot="low slot 1" type="&lt;localized hint=&quot;Tracking Enhancer II&quot;&gt;Tracking Enhancer II*&lt;/localized&gt;"/>
			<hardware slot="low slot 0" type="&lt;localized hint=&quot;Damage Control II&quot;&gt;Damage Control II*&lt;/localized&gt;"/>
			<hardware slot="hi slot 0" type="&lt;localized hint=&quot;425mm AutoCannon II&quot;&gt;425mm AutoCannon II*&lt;/localized&gt;"/>
			<hardware slot="hi slot 1" type="&lt;localized hint=&quot;425mm AutoCannon II&quot;&gt;425mm AutoCannon II*&lt;/localized&gt;"/>
			<hardware slot="hi slot 2" type="&lt;localized hint=&quot;425mm AutoCannon II&quot;&gt;425mm AutoCannon II*&lt;/localized&gt;"/>
			<hardware slot="hi slot 3" type="&lt;localized hint=&quot;425mm AutoCannon II&quot;&gt;425mm AutoCannon II*&lt;/localized&gt;"/>
			<hardware slot="hi slot 4" type="&lt;localized hint=&quot;425mm AutoCannon II&quot;&gt;425mm AutoCannon II*&lt;/localized&gt;"/>
			<hardware slot="low slot 2" type="&lt;localized hint=&quot;Republic Fleet Gyrostabilizer&quot;&gt;Republic Fleet Gyrostabilizer*&lt;/localized&gt;"/>
			<hardware slot="low slot 3" type="&lt;localized hint=&quot;Republic Fleet Gyrostabilizer&quot;&gt;Republic Fleet Gyrostabilizer*&lt;/localized&gt;"/>
			<hardware slot="low slot 4" type="&lt;localized hint=&quot;Republic Fleet Gyrostabilizer&quot;&gt;Republic Fleet Gyrostabilizer*&lt;/localized&gt;"/>
			<hardware slot="med slot 0" type="&lt;localized hint=&quot;Federation Navy Stasis Webifier&quot;&gt;Federation Navy Stasis Webifier*&lt;/localized&gt;"/>
			<hardware slot="med slot 1" type="&lt;localized hint=&quot;Federation Navy Stasis Webifier&quot;&gt;Federation Navy Stasis Webifier*&lt;/localized&gt;"/>
			<hardware slot="med slot 2" type="&lt;localized hint=&quot;Federation Navy Stasis Webifier&quot;&gt;Federation Navy Stasis Webifier*&lt;/localized&gt;"/>
			<hardware slot="med slot 3" type="&lt;localized hint=&quot;Federation Navy Stasis Webifier&quot;&gt;Federation Navy Stasis Webifier*&lt;/localized&gt;"/>
			<hardware qty="2" slot="drone bay" type="&lt;localized hint=&quot;Garde II&quot;&gt;Garde II*&lt;/localized&gt;"/>
			<hardware slot="subsystem slot 2" type="&lt;localized hint=&quot;Loki Defensive - Adaptive Shielding&quot;&gt;Loki Defensive - Adaptive Shielding*&lt;/localized&gt;"/>
			<hardware slot="subsystem slot 0" type="&lt;localized hint=&quot;Loki Electronics - Immobility Drivers&quot;&gt;Loki Electronics - Immobility Drivers*&lt;/localized&gt;"/>
			<hardware slot="subsystem slot 3" type="&lt;localized hint=&quot;Loki Propulsion - Chassis Optimization&quot;&gt;Loki Propulsion - Chassis Optimization*&lt;/localized&gt;"/>
			<hardware slot="subsystem slot 4" type="&lt;localized hint=&quot;Loki Offensive - Projectile Scoping Array&quot;&gt;Loki Offensive - Projectile Scoping Array*&lt;/localized&gt;"/>
			<hardware slot="subsystem slot 1" type="&lt;localized hint=&quot;Loki Engineering - Supplemental Coolant Injector&quot;&gt;Loki Engineering - Supplemental Coolant Injector*&lt;/localized&gt;"/>
			<hardware slot="rig slot 2" type="&lt;localized hint=&quot;Medium Anti-Explosive Screen Reinforcer II&quot;&gt;Medium Anti-Explosive Screen Reinforcer II*&lt;/localized&gt;"/>
			<hardware slot="rig slot 0" type="&lt;localized hint=&quot;Medium Anti-Kinetic Screen Reinforcer II&quot;&gt;Medium Anti-Kinetic Screen Reinforcer II*&lt;/localized&gt;"/>
			<hardware slot="rig slot 1" type="&lt;localized hint=&quot;Medium Core Defense Field Extender II&quot;&gt;Medium Core Defense Field Extender II*&lt;/localized&gt;"/>
			<hardware slot="med slot 4" type="&lt;localized hint=&quot;Republic Fleet Large Shield Extender&quot;&gt;Republic Fleet Large Shield Extender*&lt;/localized&gt;"/>
		</fitting>
```

To me, we should be able to just extract the type information from the export, without all the additional additions this PR does (without looking to see what they attempt to acomplish).

@jeffy-g thanks in advance for the clarifications :)

**Comment by jeffy-g** [comment]
thanks for reply :-)

I am at work now.
I will report about various phenomena when I return

**Comment by jeffy-g** [comment]
Also, in my environment there was no problem with 250 fit indication

**Comment by jeffy-g** [comment]
About localizetion
---
For languages other than English, in the xml fit data exported by EVE client,
A **`localized`** tag is embedded in the `type` attribute of **`shipType`**, **`hardware`** tag

However, in Russian and German, there seems to be no data of the translation item name yet, so the **`localized`** tag does not make sense
Therefore, the English item name is recorded in `hint` attribute, text content of **`localized`** tag

On the other hand, in French and Japanese there are data of translation item names,
In **`localized`** tag, translation item name and English item name are recorded

**The content of this French and Japanese XML data is a problem**

XML export of a Kronos fit(at English:
>     <fittings>
>         <fitting name="--&amp;gt; Kronos">
>             <description value="&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;Resist reinforced fit -&amp;gt; &lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#fff7931e&quot;&gt;&lt;a href=&quot;fitting:28661:11648;1:12068;1:11269;1:24427;1:3540;1:33400;1:3186;4:16499;1:26292;1:26296;1:4025;1:1978;1:5051;1:11644;1:11642;1:11646;2:31880;5:33681;1:31874;5:21426;2320:12787;2000:28999;1:41490;1:12791;2000::&quot;&gt;Armor&lt;/a&gt;&lt;br&gt;&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;this is mod link text :&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#ffffa600&quot;&gt;&lt;a href=&quot;showinfo:4025&quot;&gt;X5 Enduring Stasis Webifier&lt;/a&gt;&lt;/font&gt;"/>
>             <shipType value="Kronos"/>
>             <hardware slot="rig slot 1" type="Large Anti-Thermal Pump II"/>
>             <hardware slot="rig slot 0" type="Large Nanobot Accelerator II"/>
>             <hardware qty="10" slot="drone bay" type="'Augmented' Vespa"/>
>             <hardware qty="5" slot="drone bay" type="Federation Navy Hobgoblin"/>
>             <hardware slot="hi slot 7" type="Neutron Blaster Cannon II"/>
>             <hardware slot="hi slot 6" type="Neutron Blaster Cannon II"/>
>             <hardware slot="hi slot 5" type="Neutron Blaster Cannon II"/>
>             <hardware slot="hi slot 4" type="Neutron Blaster Cannon II"/>
>             <hardware slot="hi slot 3" type="Drone Link Augmentor II"/>
>             <hardware slot="hi slot 1" type="Heavy Knave Scoped Energy Nosferatu"/>
>             <hardware slot="hi slot 0" type="Bastion Module I"/>
>             <hardware slot="med slot 3" type="Heavy Electrochemical Capacitor Booster I"/>
>             <hardware slot="med slot 2" type="Tracking Computer II"/>
>             <hardware slot="med slot 1" type="X5 Enduring Stasis Webifier"/>
>             <hardware slot="med slot 0" type="500MN Quad LiF Restrained Microwarpdrive"/>
>             <hardware slot="low slot 6" type="Large Armor Repairer II"/>
>             <hardware slot="low slot 5" type="Energized Adaptive Nano Membrane II"/>
>             <hardware slot="low slot 4" type="Reactive Armor Hardener"/>
>             <hardware slot="low slot 3" type="Magnetic Field Stabilizer II"/>
>             <hardware slot="low slot 2" type="Armor Thermal Hardener II"/>
>             <hardware slot="low slot 1" type="Magnetic Field Stabilizer II"/>
>             <hardware slot="low slot 0" type="Armor EM Hardener II"/>
>             <hardware qty="4640" slot="cargo" type="Null L"/>
>             <hardware qty="2280" slot="cargo" type="Void L"/>
>             <hardware qty="2000" slot="cargo" type="Dread Guristas Uranium Charge L"/>
>             <hardware qty="2" slot="cargo" type="Optimal Range Script"/>
>             <hardware qty="2" slot="cargo" type="Navy Cap Booster 3200"/>
>         </fitting>
>     </fittings>

I'm a Japanese.
if i refer to the phenomenon in the Japanese setting,

**Settings -> Language tab -> Check Japanese**

>     Important Names:
>      - English Replacement
>         <fittings>
>             <fitting name="$$$--&amp;gt; Kronos">
>                 <description value="&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;Resist reinforced fit -&amp;gt; &lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#fff7931e&quot;&gt;&lt;a href=&quot;fitting:28661:11648;1:12068;1:11269;1:24427;1:3540;1:33400;1:3186;4:16499;1:26292;1:26296;1:4025;1:1978;1:5051;1:11644;1:11642;1:11646;2:31880;5:33681;1:31874;5:21426;2320:12787;2000:28999;1:41490;1:12791;2000::&quot;&gt;Armor&lt;/a&gt;&lt;br&gt;&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;this is mod link text :&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#ffffa600&quot;&gt;&lt;a href=&quot;showinfo:4025&quot;&gt;X5 Enduring Stasis Webifier&lt;/a&gt;&lt;/font&gt;"/>
>                 <shipType value="&lt;localized hint=&quot;クロノス&quot;&gt;Kronos*&lt;/localized&gt;"/>
>                 <hardware slot="rig slot 1" type="&lt;localized hint=&quot;大型アンチサーマルポンプ2&quot;&gt;Large Anti-Thermal Pump II*&lt;/localized&gt;"/>
>                 <hardware slot="rig slot 0" type="&lt;localized hint=&quot;大型ナノボットアクセラレーターII&quot;&gt;Large Nanobot Accelerator II*&lt;/localized&gt;"/>
>                 <hardware qty="10" slot="drone bay" type="&lt;localized hint=&quot;「強化型」ベスパ&quot;&gt;'Augmented' Vespa*&lt;/localized&gt;"/>
>                 <hardware qty="5" slot="drone bay" type="&lt;localized hint=&quot;連邦海軍仕様ホブゴブリン&quot;&gt;Federation Navy Hobgoblin*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 7" type="&lt;localized hint=&quot;中性子ブラスターキャノンII&quot;&gt;Neutron Blaster Cannon II*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 6" type="&lt;localized hint=&quot;中性子ブラスターキャノンII&quot;&gt;Neutron Blaster Cannon II*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 5" type="&lt;localized hint=&quot;中性子ブラスターキャノンII&quot;&gt;Neutron Blaster Cannon II*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 4" type="&lt;localized hint=&quot;中性子ブラスターキャノンII&quot;&gt;Neutron Blaster Cannon II*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 3" type="&lt;localized hint=&quot;ドローンリンクオーグメンターII&quot;&gt;Drone Link Augmentor II*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 1" type="&lt;localized hint=&quot;ヘビーネイブ・スコープエネルギーノスフェラトゥ&quot;&gt;Heavy Knave Scoped Energy Nosferatu*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 0" type="&lt;localized hint=&quot;バッションモジュールI&quot;&gt;Bastion Module I*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 3" type="&lt;localized hint=&quot;大型電子化合キャパシタブースターI&quot;&gt;Heavy Electrochemical Capacitor Booster I*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 2" type="&lt;localized hint=&quot;トラッキングコンピューターII&quot;&gt;Tracking Computer II*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 1" type="&lt;localized hint=&quot;X5持続型ステイシスウェビファイヤー&quot;&gt;X5 Enduring Stasis Webifier*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 0" type="&lt;localized hint=&quot;500MNクワッドリフ抑制型マイクロワープドライブ&quot;&gt;500MN Quad LiF Restrained Microwarpdrive*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 6" type="&lt;localized hint=&quot;大型アーマーリペアラII&quot;&gt;Large Armor Repairer II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 5" type="&lt;localized hint=&quot;電磁加工ナノ対応装甲II&quot;&gt;Energized Adaptive Nano Membrane II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 4" type="&lt;localized hint=&quot;リアクティブアーマーハードナー&quot;&gt;Reactive Armor Hardener*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 3" type="&lt;localized hint=&quot;磁場制御機II&quot;&gt;Magnetic Field Stabilizer II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 2" type="&lt;localized hint=&quot;サーマルアーマーハードナー2&quot;&gt;Armor Thermal Hardener II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 1" type="&lt;localized hint=&quot;磁場制御機II&quot;&gt;Magnetic Field Stabilizer II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 0" type="&lt;localized hint=&quot;アーマーEMハードナーII&quot;&gt;Armor EM Hardener II*&lt;/localized&gt;"/>
>                 <hardware qty="4640" slot="cargo" type="&lt;localized hint=&quot;ヌル弾L&quot;&gt;Null L*&lt;/localized&gt;"/>
>                 <hardware qty="2280" slot="cargo" type="&lt;localized hint=&quot;ボイド弾L&quot;&gt;Void L*&lt;/localized&gt;"/>
>                 <hardware qty="2000" slot="cargo" type="&lt;localized hint=&quot;ドレッドガリスタスウラン弾L&quot;&gt;Dread Guristas Uranium Charge L*&lt;/localized&gt;"/>
>                 <hardware qty="2" slot="cargo" type="&lt;localized hint=&quot;最適射程距離スクリプト&quot;&gt;Optimal Range Script*&lt;/localized&gt;"/>
>                 <hardware qty="2" slot="cargo" type="&lt;localized hint=&quot;海軍仕様キャパシタブースター3200&quot;&gt;Navy Cap Booster 3200*&lt;/localized&gt;"/>
>             </fitting>
>         </fittings>
> 
>      - 日本語
>         <fittings>
>             <fitting name="$$$--&amp;gt; Kronos">
>                 <description value="&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;Resist reinforced fit -&amp;gt; &lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#fff7931e&quot;&gt;&lt;a href=&quot;fitting:28661:11648;1:12068;1:11269;1:24427;1:3540;1:33400;1:3186;4:16499;1:26292;1:26296;1:4025;1:1978;1:5051;1:11644;1:11642;1:11646;2:31880;5:33681;1:31874;5:21426;2320:12787;2000:28999;1:41490;1:12791;2000::&quot;&gt;Armor&lt;/a&gt;&lt;br&gt;&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#bfffffff&quot;&gt;this is mod link text :&lt;/font&gt;&lt;font size=&quot;12&quot; color=&quot;#ffffa600&quot;&gt;&lt;a href=&quot;showinfo:4025&quot;&gt;X5 Enduring Stasis Webifier&lt;/a&gt;&lt;/font&gt;"/>
>                 <shipType value="&lt;localized hint=&quot;Kronos&quot;&gt;クロノス*&lt;/localized&gt;"/>
>                 <hardware slot="rig slot 1" type="&lt;localized hint=&quot;Large Anti-Thermal Pump II&quot;&gt;大型アンチサーマルポンプ2*&lt;/localized&gt;"/>
>                 <hardware slot="rig slot 0" type="&lt;localized hint=&quot;Large Nanobot Accelerator II&quot;&gt;大型ナノボットアクセラレーターII*&lt;/localized&gt;"/>
>                 <hardware qty="10" slot="drone bay" type="&lt;localized hint=&quot;'Augmented' Vespa&quot;&gt;「強化型」ベスパ*&lt;/localized&gt;"/>
>                 <hardware qty="5" slot="drone bay" type="&lt;localized hint=&quot;Federation Navy Hobgoblin&quot;&gt;連邦海軍仕様ホブゴブリン*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 7" type="&lt;localized hint=&quot;Neutron Blaster Cannon II&quot;&gt;中性子ブラスターキャノンII*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 6" type="&lt;localized hint=&quot;Neutron Blaster Cannon II&quot;&gt;中性子ブラスターキャノンII*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 5" type="&lt;localized hint=&quot;Neutron Blaster Cannon II&quot;&gt;中性子ブラスターキャノンII*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 4" type="&lt;localized hint=&quot;Neutron Blaster Cannon II&quot;&gt;中性子ブラスターキャノンII*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 3" type="&lt;localized hint=&quot;Drone Link Augmentor II&quot;&gt;ドローンリンクオーグメンターII*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 1" type="&lt;localized hint=&quot;Heavy Knave Scoped Energy Nosferatu&quot;&gt;ヘビーネイブ・スコープエネルギーノスフェラトゥ*&lt;/localized&gt;"/>
>                 <hardware slot="hi slot 0" type="&lt;localized hint=&quot;Bastion Module I&quot;&gt;バッションモジュールI*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 3" type="&lt;localized hint=&quot;Heavy Electrochemical Capacitor Booster I&quot;&gt;大型電子化合キャパシタブースターI*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 2" type="&lt;localized hint=&quot;Tracking Computer II&quot;&gt;トラッキングコンピューターII*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 1" type="&lt;localized hint=&quot;X5 Enduring Stasis Webifier&quot;&gt;X5持続型ステイシスウェビファイヤー*&lt;/localized&gt;"/>
>                 <hardware slot="med slot 0" type="&lt;localized hint=&quot;500MN Quad LiF Restrained Microwarpdrive&quot;&gt;500MNクワッドリフ抑制型マイクロワープドライブ*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 6" type="&lt;localized hint=&quot;Large Armor Repairer II&quot;&gt;大型アーマーリペアラII*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 5" type="&lt;localized hint=&quot;Energized Adaptive Nano Membrane II&quot;&gt;電磁加工ナノ対応装甲II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 4" type="&lt;localized hint=&quot;Reactive Armor Hardener&quot;&gt;リアクティブアーマーハードナー*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 3" type="&lt;localized hint=&quot;Magnetic Field Stabilizer II&quot;&gt;磁場制御機II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 2" type="&lt;localized hint=&quot;Armor Thermal Hardener II&quot;&gt;サーマルアーマーハードナー2*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 1" type="&lt;localized hint=&quot;Magnetic Field Stabilizer II&quot;&gt;磁場制御機II*&lt;/localized&gt;"/>
>                 <hardware slot="low slot 0" type="&lt;localized hint=&quot;Armor EM Hardener II&quot;&gt;アーマーEMハードナーII*&lt;/localized&gt;"/>
>                 <hardware qty="4640" slot="cargo" type="&lt;localized hint=&quot;Null L&quot;&gt;ヌル弾L*&lt;/localized&gt;"/>
>                 <hardware qty="2280" slot="cargo" type="&lt;localized hint=&quot;Void L&quot;&gt;ボイド弾L*&lt;/localized&gt;"/>
>                 <hardware qty="2000" slot="cargo" type="&lt;localized hint=&quot;Dread Guristas Uranium Charge L&quot;&gt;ドレッドガリスタスウラン弾L*&lt;/localized&gt;"/>
>                 <hardware qty="2" slot="cargo" type="&lt;localized hint=&quot;Optimal Range Script&quot;&gt;最適射程距離スクリプト*&lt;/localized&gt;"/>
>                 <hardware qty="2" slot="cargo" type="&lt;localized hint=&quot;Navy Cap Booster 3200&quot;&gt;海軍仕様キャパシタブースター3200*&lt;/localized&gt;"/>
>             </fitting>
>         </fittings>
> 

This is troublesome!

Depending on the settings of Important Names,  
translated item names and English item names are reversed LOL

This is also true for French

At first glance, my code written in Port.py which seems useless is the result of dealing with this problem

I used to write programs in java before, but I currently have few programs to write
Since Python came to touch only after meeting pyfa project,
There is no knowledge of optimization at language level

So, if you have a better code please change it :-)

About pyfa craches
---
Then, on the problem that pyfa crashes when importing a lot of fit data

This phenomenon occurred when importing xml file exported from EFT (1129fit)
The following is the Traceback at that time

> <b style="font-size: small">Traceback (most recent call last):
>   File "F:\ext_prg\develp\msys\1.0\home\ht\git\pyfa-org\Pyfa\gui\sfBrowserItem.py", line 274, in OnPaint
>     mdc.DrawBitmap(self.bkBitmap, 0, 0)
>   File "F:\ext_prg\develp\python27\lib\site-packages\wx-3.0-msw\wx\_gdi.py", line 3795, in DrawBitmap
>     return _gdi_.DC_DrawBitmap(*args, **kwargs)
> wx._core.PyAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap</b>

Every time scroll, this Traceback comes out...

Thanks for reading :-)

**Comment by jeffy-g** [comment]
xml file for reproducing pyfa crash
I added it as `import_crash_sample` branch to my working repository

at **windows7 64bit intel core i5-2500k memory 16G**

> tests/too-many-fits[676].xml
>         no problem
> 
> tests/too-many-fits[994].xml
>         Crash occurred


It was just filled with the Kronos fit data i mentioned earlier,
It should be enough to reproduce the near situation

**Comment by jeffy-g** [comment]
I'm now writing test code while making improvements to these changes,
Just adding the test source to the master branch could not be done.

As a result of various search, @Ebag333 work repository
We have found the necessary changes to run the test source in the "cache_fits" branch.
(Especially initialization of the database was necessary)

Should I work on development branch rather than master branch?

I think that it would be good if we can use the database for testing with the minimum necessary change

**Comment by blitzmann** [comment]
@jeffy-g thanks for the posts - it gives better clarity to the problems you faced. I will review as soon as I can, but as long as it works, I don't see a problem with it. 

Also thanks so much for the XML file that you used to cause a crash - I will definitely look into it.

> As a result of various search, @Ebag333 work repository
We have found the necessary changes to run the test source in the "cache_fits" branch.
(Especially initialization of the database was necessary)

> Should I work on development branch rather than master branch?

Not sure I understand this bit. @Ebag333's `cache_fits` branch is currently under review IIRC and not accepted, so it's best to base this on current `development` branch as that's the branch we'll be merging this into. :D

**Comment by Ebag333** [comment]
>Not sure I understand this bit. @Ebag333's cache_fits branch is currently under review IIRC and not accepted, so it's best to base this on current development branch as that's the branch we'll be merging this into. :D

I think he meant he got tests working.  Which is good.

Dev should have a number of examples on using tests though.

**Comment by jeffy-g** [comment]
I pushed the result of this time to github as "ebag333_cache_fits_edit" earlier,
but failed in the test of Travis CI...

When running py.test on my PyCharm, the test code was executed normally, but ...
Well, will progress little by little :-D

**Comment by Ebag333** [comment]
```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_fitcache.py ____________________
[31mImportError while importing test module '/home/travis/build/jeffy-g/Pyfa-dev/tests/test_fitcache.py'.
Original error message:
'No module named _development.helpers'
Make sure your test modules/packages have valid Python names.[0m
__________________ ERROR collecting tests/test_unread_desc.py __________________
[31mImportError while importing test module '/home/travis/build/jeffy-g/Pyfa-dev/tests/test_unread_desc.py'.
Original error message:
'No module named _development.helpers'
Make sure your test modules/packages have valid Python names.[0m
```

Unlike the local pyCharm interpreter, the local path isn't automagically put in for you.  You have to be explicit.

So, as a work around, we add the root path to your python paths environment variable.  We use this bit of code:

```
# Add root folder to python paths
# This must be done on every test in order to pass in Travis
import os
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.realpath(os.path.join(script_dir, '..', '..', '..')))
```

Note that the number of `'..'` you have must match the depth.  So if you're only two folders deep, then you'd need two.  This test example was three deep (`root\tests\test_modules\test_eos\`) so needed three.

Make sure you have this code at the very top, and it's got the right number to put a reference back to the root.

**Comment by jeffy-g** [comment]
> So, as a work around, we add the root path to your python paths environment variable.

yea, since PyCharm resolves these things, I understood that I did not need to specify explicitly.
but, it seems that eventually it was necessary to change ".travis.yml". B-)

thanks

**Comment by Ebag333** [comment]
>but, it seems that eventually it was necessary to change ".travis.yml". B-)

What did you change in `.travis.yml`?

**Comment by jeffy-g** [comment]
A new problem occurred when solving the root path problem

> ___________________ ERROR collecting tests/test_fitcache.py ____________________
> ImportError while importing test module '/home/travis/build/jeffy-g/Pyfa-dev/tests/test_fitcache.py'.
> Original error message:
> 'No module named wx'
> Make sure your test modules/packages have valid Python names.
> __________________ ERROR collecting tests/test_unread_desc.py __________________
> ImportError while importing test module '/home/travis/build/jeffy-g/Pyfa-dev/tests/test_unread_desc.py'.
> Original error message:
> 'No module named wx'
> Make sure your test modules/packages have valid Python names.

Since wx module is not found,
I looked for the necessary description and I got to your `fit_pointer` branch

I just copied ".travis.yml" from there :-P

`.travis.yml`
```
language: python
cache: pip
python:
  - '2.7'
env:
  - TOXENV=pep8
addons:
  apt:
    packages:
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ru language-pack-he language-pack-zh-hans
  - pip install tox
  # We're not actually installing Tox, but have to run it before we install wxPython via Conda. This is fugly but vOv
  - tox
  # get Conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  # install wxPython 3.0.0.0
  - conda install -c https://conda.anaconda.org/travis wxpython
before_script:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - py.test --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - pip install -r requirements_build_linux.txt
```

**Comment by Ebag333** [comment]
Ah, I see.

Yup. That makes it work. ;)

**Comment by blitzmann** [comment]
@jeffy-g Sorry I never got back to you on the status of this. But as you can tell by the merge, all is well :) I reviewed it about a week ago and made some tweaks a few days ago. Everything looked good - I tested it as best I could and didn't find anything concerning. You definitely used some patterns that I'm not familiar with, but it was really interesting to see how you implemented it, and I think I can learn a few things from what was presented here. :D 

Good job! 👍

**Comment by jeffy-g** [comment]
thanks for accept the my PR
Since I am doing different things now, I am thinking to make improvements if my heart is good :-)

**Pull request merged**
