### PR TITLE
Market meta category options

### PR DESCRIPTION
**Pull request by DarkFenX**
- [x] create separate preferences category for price & market options
- [x] make preference dialog bigger under GTK to get rid of horizontal scrolling
- [x] move existing market-panel related options to new preferences panel (item shortcuts, price source and system, market search delay)
- [x] move "total" price options to new preferences panel
- [x] add option which controls metagroup behavior during market jump
- [x] add option which controls metagroup behavior when no items are in group with current filter
- [x] add option which controls metagroup behavior during item search
- [x] add option which controls metagroup behavior when selecting market group in market browser
- [x] rework price panel context menu to remove cache drop item, and move drones / cargo / character directly to main context menu
- [x] check if it's possible to drop selection from market group when starting a search w/o changing scroll position in market tree panel
- [x] change icon of the new preference group

### CODE REVIEW

**Comment by DarkFenX** [comment]
Preferences:

image

image

**Comment by DarkFenX** [comment]
All the new logic is implemented besides search-specific mode. I have no yet settled on how it should behave. I have 3 possible variants in mind:

1) no changes
2) enable all meta groups
3) enable all meta groups (preserve metagroup state pre-search and restore it once user selects market group in browser or does market jump)

But i do not know which should be exposed to options, maybe all 3.

**Comment by DarkFenX** [comment]
@blitzmann in metaButton.py, there's a workaround for some bug:
```
    def setMetaAvailable(self, isAvailable):
        self.Enable(isAvailable)
        # need to also SetValue(False) for windows because Enabled=False AND SetValue(True) looks enabled.
        if not isAvailable:
            self.SetValue(False)
```
Could you check if it's still needed? I think it would be beneficial to see button state even while it's disabled. Makes it easier to understand what will be selected when you click market group with all meta categories available.

If it's bugging out only on windows - i will change code to make it windows-specific.

**Comment by DarkFenX** [comment]
I've implemented all the logic i wanted to implement i think. The only remaining issue i noticed is that when in search mode user clicks already selected item in market tree, it doesn't get back to normal mode (which has always been like that, but still a little annoying). Is there a way to let user select already selected market group during search (or, rather, let market browser know one way or another)?

**Comment by burnsypet** [comment]
@DarkFenX I built your branch on Mac and ran through some scenarios and it looks great I could not find any issues, but I have two questions:

- Is it possible to have an option to enable all the available meta buttons when navigating between market groups? For example if I have all available Damage Control buttons enabled (Normal, Faction, Officer) and then change to Energized Adaptive Platings, the enabled buttons does not expand to include Complex which is available for this market group. It's possible to achieve this at the moment, but you have to manually enable all of the buttons by going to a group that has them all available first.

- How do we plan to communicate to users that the context menus are now located in a different place?  It felt a bit jarring not being able to follow my learned route for changing these options, and if I hadn't re-read your post I wouldn't have guessed there was a new Preferences tab especially since I don't use the Preferences menu very often.

**Comment by DarkFenX** [comment]
@burnsypet well, it depends on what's the use-case. If i imagine situation right, i can see two options to resolve that:

- make disabled meta buttons togglable when ctrl is pressed
- introduce another set of options which kicks in when you click market group in market group tree (not via market jump). Obvious choices would be "no changes" and "enable all meta buttons"

What would you prefer and why? If you prefer second - do you see other option values which might be useful?

Regarding communicating to users - first of all, why do you ask, because of the price menu? How often did you use it and why? As for communicating - we will have to come up with something within scope of #1887 (which I also wanted to implement before next release), here I just did small part of it related to prices.

**Comment by burnsypet** [comment]
I would prefer this option:

> introduce another set of options which kicks in when you click market group in market group tree (not via market jump). Obvious options would be "no changes" and "enable all meta buttons"

If it was possible to toggle the buttons when they were not available for the market group I think it would cause confusion.

My use case for the price context menu is:

If I want to check the cost of a fitting without drones/ammo because I know that I own those already then I right click the total cost and toggle off the ones I don't want to see. I frequently toggle these options when looking at fits I import from zKillboard, but when I create a new fit from nothing myself I prefer to have the total price contain everything. I usually toggle these options multiple times per session.

I can understand that for some users this might be a setting they set once and then forget about it, but it is a toggle that I use regularly and moving it to preferences increases the effort required.

**Comment by DarkFenX** [comment]
Ok then my bad for removing them, i will put them back later.

**Comment by DarkFenX** [comment]
I restored old context menus and added settings group for market group selection. However, i did not find quick way to implement it so will do that later.

Also, regarding pricing options, i think that context menu should show drones/cargo/character menu directly rather than subitem - for convenience (and clear prices menu item should be removed).

**Comment by DarkFenX** [comment]
@burnsypet I've added full support for this option, now just some UI polish remaining.

**Comment by DarkFenX** [comment]
I finished all the changes i wanted to implement, looking for feedback on following 2 things:

1) I've added market group unselection upon using search. Does it work under windows/mac without side-effects (like switching scrolling position)?
2) Meta button windows-specific workaround:
```
    def setMetaAvailable(self, isAvailable):
        self.Enable(isAvailable)
        # need to also SetValue(False) for windows because Enabled=False AND SetValue(True) looks enabled.
        if not isAvailable and "wxMSW" in wx.PlatformInfo:
            self.SetValue(False)
```
Is it still needed?

**Comment by DarkFenX** [comment]
I'm going to merge it now, but still would like to get answers.

**Comment by DarkFenX** [comment]
1) Works on windows
2) It's still needed

**Pull request merged**
