### PR TITLE
Damage and Target profile changes for "Depths of the abyss" patch. Issue #2265

### PR DESCRIPTION
**Pull request by Neugeniko**

### CODE REVIEW

**Comment by blitzmann** [comment]
Where did you get these updated values? Are they in the SDE now? tbh I haven't looked for them in years but I remember they used to be figured out manually.

This PR looks okay to me for value changes and adding profiles, but I've been pretty far removed from eve patches to really know what's up, so I'll wait for @DarkFenX to weigh in.

**Comment by Neugeniko** [comment]
They are in esi and the client and based on a unweighted sum of
 dps and tank for a category/npc group. Generally good for a profile per
category
/npc group because npcs are similar but the 'All' categories are very rough
cos of the unweighted sums.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Neugeniko** [comment]
Here is the spreadsheet I use for abyssal stuff. I do similar sheets for
other content.


 Pyfa Abyssal NPC Info by Neugeniko v 0.8
<https://docs.google.com/spreadsheets/d/1y1c-dpVb0xROT0uXuXszVUenOWgCq-a3_x1YKJI3fEA/edit?usp=drive_web>

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Neugeniko** [comment]
Closing to add recent changes to tanks of concord ships.

**Pull request closed without merging**
