### PR TITLE
#1784

### PR DESCRIPTION
**Pull request by petosorus**
For issue #1784.
NotesView doesn't work like the others because it does not implement Display.
The notes tab also does not update immediately as the others. It does update at least when a fit is closed, so the idea of the development is still there: opening a fit, seeing there are notes.

### CODE REVIEW

**Comment by DarkFenX** [comment]
Without knowing about this PR (didn't check those which were submitted during my absence), I've implemented extended version of this PR in 2.11.1. It now shows amount of active / all items (according to prererences) in tab titles.

Now as feature is there already, I am closing it.

**Comment by DarkFenX** [comment]
Oh and I also did not add support to Notes tab, although due to different reasons (no idea what to show there, just mere presence of text?)

**Comment by petosorus** [comment]
I forgot about this one.
It looks like mere presence of text yeah.

**Comment by DarkFenX** [comment]
Added it in 5f7d9aea893e8120c1a8ecb1052a1ce7fec0a02e - shows amount of text characters

**Pull request closed without merging**
