### PR TITLE
Redefine operation of numerous effects.

### PR DESCRIPTION
**Pull request by Neugeniko**
Added the code to turn off MJDs for various modules. Also ensure they operate correctly depending on script loaded. Various other corrections to operation. See Issue #1456 for further details.

### CODE REVIEW

**Comment by burnsypet** [comment]
Looks good.

I think I was the last person to touch this when I was adding the warp scramble strength thing, guess I just totally forgot that MJDs existed when I did that.

**Comment by Neugeniko** [comment]
One thing that is nice now is that we can see things in the in game simulator. It doesn't help with projections thou, and we still need someone to test those on the test server usually with two accounts.

Yeah looks like the travis check is due to line length. The appveyor fail seems outside the scope of the pr. I'll let blitzmann handle any changes until I get familiar with the requirements.

**Comment by Neugeniko** [comment]
Corrected the structure missile guidance enhancer effect.

**Comment by Neugeniko** [comment]
Added a effects file for the Standup Warp Disruption Burst Projector (shared with the super based equivalent).

**Comment by blitzmann** [comment]
>Edit: Just noticed the code check is kicking off, I think it's because you've included surplus extra lines or exceeded the character limit of 165 in warpdisruptsphere.py

The py3 branch will remain in a failing state in travis since I'm not worried about keeping code guidelines in placed right now as development on this branch is fast going. AppVeyor also breaks since there's new build processes with this branch, and I haven't had the time or motivation to fix it yet. both of these will be back to normal by the time 2.x goes stable and is released.

@burnsypet weren't you working on a cap delta thing? how's that coming along?

**Pull request merged**
