### PR TITLE
Fighters for export and import functions

### PR DESCRIPTION
**Pull request by IndictionEve**
Fighter Support added for
- importDNA
- importEFT
- importEFTCfg
- importXML

- exportDNA
- exportXML

Solves #800 

I added a new property `fighterSquadronMaxSize`.
`amountActive `has the same value by default but is different as soon as the number of fighters set.

### CODE REVIEW

**Comment by blitzmann** [comment]
@IndictionEve I'm going to assume this has been tested with eve imports / exports as well? How about CREST export / import?

**Comment by blitzmann** [comment]
@IndictionEve pls respond. Release is going to be tomorrow barring any major bug report between now and then

**Comment by IndictionEve** [comment]
sorry for the late response:
i used eve and eft import and exports for testing.

i really want to add fighter support for crest, too. but i am not able to debug into the entire crest tree. (breakpoints do not trigger)

**Comment by IndictionEve** [comment]
found a way by extracting the crest request manually.

Tested with all fighter classes (light / heavy / utility):
- CREST import / export and eve client
- CREST import / export to clipboard
- EFT import / export and eve client
- EFT import / export and EFT
- Multibuy export and eve client
- DNA import / export by checking the output string
- XML import / export by checking the output string

**Comment by blitzmann** [comment]
gonna trust ya on this  - don't have the ability to test myself at this time

**Pull request merged**
