### PR TITLE
Debian specific files

### PR DESCRIPTION
**Pull request by AdamMajer**
These are debian specific files to make a .deb package. This then can be installed on Debian or derivatives or distributions that use .deb format (eg. Ubuntu).

I'm using Pyfa under Debian, and a package is useful.

### CODE REVIEW

**Comment by blitzmann** [comment]
I am somewhat hesitant of merging this for the following reasons:

1) While pyfa supports Linux, I'm more inclined to keep the main repository distro-agnostic. This is because I cannot test most distro's, and honestly don't want to be responsible for maintaining packages for various distros. I do, however, support third-party packaging such as Arch's AUR or your .deb files.
2) I am not at all familiar with Debian packaging system to be comfortable including it in the repo right now. Besides adding debian-specific files to the repo so that user's can create their own package, what does this acomplish?

As a side note, and related to 2), I see the `debian/watch` file. How does this work? Does it automatically download and patch the package when a new release is available when updating the systems packages? Now that would be neat, but again, I don't know much about their system.

**Comment by AdamMajer** [comment]
That's fine. If you don't mind, can you point Debian/Ubuntu users to my repository in your README.md? I maintain Debian package for pyfa, which should work fine with Ubuntu and others. RPM is on SUSE's Build Service - I'll add a link to that too from my repository.

`debian/watch` file is used by `uscan` to automatically download latest release versions. This automatically calls `uupdate` - It's mostly a convenience and automation utility. Many times it's enough to do,

    uscan
    cd ../<new_version>
    debuild

and you have your new package ready.

**Comment by blitzmann** [comment]
I will definitely add it to the README file. I've been meaning to add a list of third party packages to it for ages.

Let me know if there is something I can do to make packaging smoother. =)

**Comment by AdamMajer** [comment]
Thank you.

The only thing that you could do to make packaging smoother is not to make radical changes to the package, and I think you are already doing this :smile:

But you could sign release tags or changelog entries as per #262 . Signed archives allow people to verify that source code is authentic and not tampered with by a 3rd party.

**Comment by altyr** [comment]
@AdamMajer In case you're not aware of it, there there are Pyfa packages in the playdeb repository: [http://www.playdeb.net/game/Python%20Fitting%20Assistant](http://www.playdeb.net/game/Python%20Fitting%20Assistant)

(assuming those aren't maintained by you already)

**Pull request closed without merging**
