### PR TITLE
Activate fighter standard attack and limit active fighters

### PR DESCRIPTION
**Pull request by IndictionEve**
#755 @Rylleyryelle said: 
> i as a user, would much prefer to have to DISABLE what i dont want running on them, rather than having to enable every stupid bleepity bleeping thing every time i change out a fighter to tinker.
- Adding Fighters: Activate all implemented abilities by default
-- Because you don't add deactivated modules to fittings, too
-- The usability of fighters is not optimal, so let's make it a little bit easier for the daily use.
- Adding Fighters: Deactivate fighter groups if more than the maximum number of active fighters are in bay (soft limit)
--It is still possible to activate more fighter then allowed for testing, switching fighters, etc...

### CODE REVIEW

**Comment by Ebag333** [comment]
If I import a carrier with 1 million fighters on them, will they all  be activated? :)

**Comment by IndictionEve** [comment]
Nope, nothing changes to the current behavior.
You have to add a fighter in pyfa for the new mechanics.

**Comment by IndictionEve** [comment]
Thanks for the import tip, seems like we have a issue over here #800

**Comment by Ebag333** [comment]
Seems like it.

My only concern was that a number of carriers can have a _lot_ of spare fighters, it'd be more painful to turn them off manually than turn the (relatively) few that it has tubes for on.

But sounds like that's not an issue.

**Comment by blitzmann** [comment]
Firstly, I am still not sold on activating them by default. It would be best to activate the 'standard' attack by default if there's an easy way to get to that programatically (would probably have to hard code effects which we want to auto-activate). So, instead of 

```
for ability in fighter.abilities:
                    ability.active = True if ability.effect.isImplemented else False
```

it would be 

```
for ability in fighter.abilities:
                    ability.active = True if ability.effect.isImplemented and ability.effect.name in ("effect1", "effect2") else False
```

(or however you get the name of the effect, can't remember off the top of my head)

I am open to counter points on this though. :)

Secondly, I do like the soft limit you've placed when adding fighters. Nice touch, and definitely want to keep that regardless of what we do with the fighter abilities.

**Comment by IndictionEve** [comment]
Basically it's about why do you want to add fighters to your fitting: 
First of all you want to know the max values (dps, speed)
Adding fighters without abilities is equal to a inactive fighter group: they are there but have no impact on my fitting. But this is the reason you using this tool: to simulate the effects of modules (respectively fighters).
At the second step you start experimenting with the attributes (damage without rockets, speed without propmod, etc.)
In the end you got a feeling for the maximum rating and everything between. 

However your idea just activate the 'standard attack' looks like the best solution to me.
I asked 15 guys out of my alliance what kind of behavior they expect if they add fighter to a fitting, without telling them any options: 
11 of them expecting an active 'standard attack'  
4 of them 'everything activated'
'nothing activated ' was no option for them.
But hard code abilities is something I don't like, because you have to look after the changes  every update to make sure all standard attacks are set as wanted.

**Comment by Ebag333** [comment]
>Basically it's about why do you want to add fighters to your fitting: 
>First of all you want to know the max values (dps, speed)

I agree with this.

I'd love to see a a "standard attack active" option, but since there's no default we're stuck with hard coding something, which is fugly.

Basically I'd put it in this order:
1. Standard attack on, special off
2. All attacks on
3. All attacks off

My only concern is that we make sure we don't enable all the fighters (so you don't have to click ten million times to turn *OFF* fighter attacks), the soft limit should take care of that (I hope).

If we have to hard code a list of attributes, I'd rather just turn on all the abilities than hard coding that list, since it's just another thing to maintain.

So yeah, pretty much what @IndictionEve said.

**Comment by IndictionEve** [comment]
Looks like I've got it.
The indicator we looking for is `ability.effect.handlerName`.
`fighterabilityattackm` is the "standard attack" for light and heavy drones.

support fighter currently have two abilities - propmod and utility (neut, web, etc)
If there is no "standard attack" all other abilities except propmods (`fighterabilitymicrowarpdrive` and `fighterabilityevasivemaneuvers`) set active.

because of this pyfa is able to handle and activate future effects (maybe mining fighters?)

**Comment by blitzmann** [comment]
I merged this in singularity branch. Excellent work.

@Ebag333's work in #804 might helping moving forward with the default effects to activate and whatnot once that's merged in. Would probably take a bit of work, and I'm not worried about it right now, but it's a thing.

**Pull request merged**
