### PR TITLE
Ascendency Patch

### PR DESCRIPTION
**Pull request by Ebag333**
PR for updates required by the Ascendency patch

### CODE REVIEW

**Comment by Ebag333** [comment]
So far I've updated the DB to the one I pulled from TQ (it's not the latest latest, but none of the recent patch notes have any more fitting related changes).

Orca effects are basically done, I've tested about half of them, need to go through the rest.

It'd be _extremely_ useful if you could merge the effect toggle PR into this branch.  That's a super handy way of testing how effects affect things.

Also, I found the export option to be incredibly useful.  Copy/paste FTW.

**Comment by Ebag333** [comment]
Just to be clear, this isn't complete yet.  So don't merge @blitzmann :)

Just submitting this so you can keep track of what I'm working on.

**Comment by blitzmann** [comment]
@Ebag333  go ahead and revert c8da8fc I already integrated this into the branch

**Comment by blitzmann** [comment]
Closing this as I've already integrated these commits into the sisi branch

**Pull request closed without merging**
