### PR TITLE
Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by wereii**
This fixes problems with wxPython and python310 where C extensions will not silently accept floats as ints in function arguments anymore.

Also see #2391

### CODE REVIEW

**Comment by Phoenix591** [comment]
well, things have come a good way it seems, on the dep_facelift branch using a patched [logbook](https://github.com/getlogbook/logbook/pull/320) it seems to be working with python 3.10 now.

**Comment by wereii** [comment]
@Phoenix591 so the plan is to eventually merge the dep_facelift changes into master, right? I thinking about switching `pyfa` on AUR to this branch.

**Comment by Phoenix591** [comment]
> @Phoenix591 so the plan is to eventually merge the dep_facelift changes into master, right? I am thinking about switching `pyfa` on AUR to this branch.

Presumably at some point, but I'm just someone who decided to try it

**Comment by DarkFenX** [comment]
The plan is to have it merged as soon as it's ready.

FYI, even on this branch, some windows still have issues - for example, implant set editor. And i think this issue has to be fixed somewhere on wx side, because all sizes pyfa passes are integer, issue happening there is somewhere deeper down.

**Comment by DarkFenX** [comment]
Closing this, as `dep_facelift` branch has had all the needed changes and will be merged to master soon

**Pull request closed without merging**
