### PR TITLE
Code cleanup enums #1862

### PR DESCRIPTION
**Pull request by IndictionEve**
Basic setup for #1862

- [x] Put all enums into cont.py
- [x] Setup a basic description
- [x] Renamed some of the enums to make their use more visible. 
- [x] Better description
- [x] More restructuring the unit by your whishes

Structure of the renamed enums:
- `Fitting*` for fit related enums
- `Esi*` for ESI related enums
- `Port*` for Export/Import related enums

### CODE REVIEW

**Comment by DarkFenX** [comment]
1) PortMultiBuyItemType should be PortMultiBuyOptions (consistency & it can easily have more options not related to item type, see price_optimize branch).
2) @blitzmann does it make sense to move port-related enums into eos const file?

**Comment by IndictionEve** [comment]
@DarkFenX 
regarding 1. Already done
regarding 3. Working on this. I want to get rid of the `esi.Enum` anyway and replace it by the Python 3 enum.

**Comment by blitzmann** [comment]
>@blitzmann does it make sense to move port-related enums into eos const file?

No, lets keep those out. the only enums that should be moves are those already in the eos module. we can talk about where the other ones can go later if need be

> Could use IntEnum and @unique where applicable, but it's fluff.

I agree, but would also caution that this could potentially change the value of certain enums if the order of the values are moved. ddSince some enums are saved as data in the database, this could potentially have consequences (like changing all mid slots to high slots lol). Personally would recommend they remain as explicit values :)

**Comment by IndictionEve** [comment]
Let's move the ESI and PORT enums into the service path. 
So we would have two central sources for enums:
1.  `eos/const.py` for _EOS_ related enums.
2.  `service/const.py` for _ESI_ and _port_ related enums.

**Comment by IndictionEve** [comment]
> EDIT: ...I was confusing it with something else (something that automatically assigns the value)

The only class where `auto()` is used in `FittingAttrGroup()`.
Do we want to change this to exlicit values?

**Comment by blitzmann** [comment]
@IndictionEve I think `FittingAttrGroup` is actually only used for the attribute grouping... ie: GUI stuff. Lets go ahead and move non-eos enums into another module (you suggested service, and I agree 😄)

**Comment by IndictionEve** [comment]
Done

**Comment by blitzmann** [comment]
I made a commit on your branch that fixes the various imports to point to the primary source, instead of where they originally were.

I want to make one more pass on the diff, but otherwise everything tested fine :)

**Comment by blitzmann** [comment]
@IndictionEve please take a look at the new commits on your branch. There were a couple bugs that I fixed, and some imports fixed. If everything looks good to you, I'll merge this in :)

**Comment by IndictionEve** [comment]
thanks! looks good. 

1.  gui/builtinItemStatsViews/itemAttributes.py 
i removed `import config` because it is marked as unused import in my IDE.
2.  gui/builtinViewColumns/state.py
changing the numeric expression by enums make sense :)
3. service/port/efs.py
Looks like my automatic refactoring failed here. Wondering why `PortEftRigSize` was unused, but didn't get any error or warnings. 

when do you plan to make a release? more then 3 month since the last official one.

**Comment by blitzmann** [comment]
>i removed import config because it is marked as unused import in my IDE.

```   if info and config.debug:
            attrName += " ({})".format(info.ID)```

PyCharm indeed shows it as unused. I'm not sure why, but it is used. /shrug

> when do you plan to make a release? more then 3 month since the last official one.

I am hoping for next week. EVE hasn't had  very many data changes recently so we haven't been pressed to update, but we'r getting to that point where I want to get one out soon

**Pull request merged**
