### PR TITLE
Handle unicode, utf8, and windows-1252

### PR DESCRIPTION
**Pull request by Ebag333**
Change most of the various `os.path` functions looking up the Pyfa root or saved data paths to point back to two functions in `config.py`.

This lets use more cleanly handle these with different unicode charcters and formatting types, and we have a central location for this if down the road we need to do something special here.

### CODE REVIEW

**Comment by blitzmann** [comment]
For future fyi, please don't include all the formatting changes in things like this - branch them off into a separate cleanup branch and request PRs from that. It makes it difficult to see what has changed and what hasn't, and for a change as low-level as this, it's important not to miss anything.

That being said, I'll take a look at this hopefully before release. :)

**Comment by Ebag333** [comment]
Fair enough, the reformatting was a bit more extensive than I thought it'd be, and I knew you were going to yell at me for it. :D

**Comment by Ebag333** [comment]
@blitzmann is there a reason that you took out the decodes for different file systems? Or am I reading that last commit wrong?

**Comment by Ebag333** [comment]
never mind. I see what you did there. 

```
mac-deprecated fails to launch, mac launches and works, has some issues with resolution that may be related to retina screens, seen here; https://puu.sh/sMHKs/b7d0514a47.png

systemspecs for reproduction: 
- Mid 2015 15” Macbook Pro (w/o discrete graphics)
- macOS 10.12.1
- No pyfa otherwise installed beforehand.
```

Correct me if I'm wrong, but the depreciated version is for older OSx versions, right?

**Comment by blitzmann** [comment]
Yes, apparently it no longer works in later versions of os x. see #780

I did manage to find a couple os x VMs last night, but haven't tested them to see if they actually still work. If they do, I'll try to test tonight as well. The retina resolution has been a problem since forever...

**Comment by blitzmann** [comment]
image

This doesn't see to work in Windows, at least with the packaged version. I used the example in #548. Haven't tried with source yet.

**Comment by blitzmann** [comment]
Also, while it doesn't solve the issue it meant to solve, I'm going to keep it in the dev branch. It doesn't break current functionality as far as I can tell.

**Comment by Ebag333** [comment]
that is one I tried that worked fine before you rewrote it. Not sure what changed to break it again. (testing on Windows)

**Comment by blitzmann** [comment]
On a more serious note:

```
Missing icon file: /home/ryan/Pyfa/imgs\gui\pyfa.png
Traceback (most recent call last):
  File "pyfa.py", line 135, in <module>
    MainFrame(options.title)
  File "/home/ryan/Pyfa/gui/mainFrame.py", line 135, in __init__
    i = wx.IconFromBitmap(BitmapLoader.getBitmap("pyfa", "gui"))
  File "/usr/lib/python2.7/dist-packages/wx-3.0/wx/_gdi.py", line 1342, in IconFromBitmap
    val = _gdi_.new_IconFromBitmap(*args, **kwargs)
ValueError: invalid null reference in method 'new_IconFromBitmap', expected argument 1 of type 'wxBitmap const &'

```

On my Linux Mint setup. This is much more problematic, as pyfa simply fails to run period. :)

**Comment by Ebag333** [comment]
Urgh, I wish you'd just left it until I had a chance to look at it.  Now I've gotta figure out what's changed between where my branch was and where you left this (before the revert).

**Comment by Ebag333** [comment]
Yeah, hate to say it but something you changed broke the fix.  Going to poke at this a bit and see if I can figure out what did....

Probably why it's not working on Linux either.

**Comment by blitzmann** [comment]
> Yeah, hate to say it but something you changed broke the fix. Going to poke at this a bit and see if I can figure out what did....

Bullshit. I checked if my -one change- broke it before I even posted, thanks. I even just now isolated your changes only and it's still broken.

Your shit's broken. Own it, fix it, move on.

**Comment by blitzmann** [comment]
FYI, this is probably where it is breaking. you most likely overlooked this bit:

https://github.com/pyfa-org/Pyfa/blob/master/gui/bitmapLoader.py#L77

Why this doesn't work on Linux but it works on Windows, I don't have a clue right now. But it's an area to start dropping `print`s in.

**Comment by Ebag333** [comment]
FYI as is it's broken on Windows. When I committed the PR, this particular test `Téléchargements` worked fine.

**Comment by Ebag333** [comment]
>FYI, this is probably where it is breaking. you most likely overlooked this bit:
>https://github.com/pyfa-org/Pyfa/blob/master/gui/bitmapLoader.py#L77

This did get missed in the original PR looks like.

**Comment by blitzmann** [comment]
> FYI as is it's broken on Windows. When I committed the PR, this particular test Téléchargements worked fine.

Be more specific. It worked with the skels? Or it worked from source? Because I can tell you without a doubt - I just built a package with your unicode path commit, and that use case does not work. Please outline your testing and what you did to determine that it worked - maybe we're both missing something here.

For reference, this is the original commit - 0d4f24

**Comment by Ebag333** [comment]
Replaced the archive files with the updated .py files. It worked.

I'm 99.9% sure that this error I ran into before. I may have fixed it and simply not committed that fix (which would be dumb on my part).  It's hard for me to tell what's going on with the PR because that branch for some reason has a bajillion commits after it.  Reverting back to the original commit has this problem, but I'm 99% sure that I didn't have a PR with just a single commit.

Given that this all was done near a month ago though, who knows.  Memory is faulty.

**Comment by blitzmann** [comment]
Just realized: `/home/ryan/Pyfa/imgs\gui\pyfa.png` Notice the inconsistent slash directions. This might be why it's breaking.

**Comment by Ebag333** [comment]
>Just realized: /home/ryan/Pyfa/imgs\gui\pyfa.png Notice the inconsistent slash directions. This might be why it's breaking.

To be fair I never claimed to test it on Linux. :)

Not sure how Linux handles alternating slashes.  This very well could be the root of that issue.

**Comment by blitzmann** [comment]
> It's hard for me to tell what's going on with the PR because that branch for some reason has a bajillion commits after it. Reverting back to the original commit has this problem, but I'm 99% sure that I didn't have a PR with just a single commit.

You did.

Are you still using GitHub app? I don't know how they display stuff, but with GitExtensions it's very easy to see what happened:

image

then a few week later: 

image

You can see that I brought the branch up to date with dev, made my commit, and then merged back into dev. Until that point, that one commit was it. 

> To be fair I never claimed to test it on Linux. :)

https://pyfa.slack.com/archives/D2Q139FTJ/p1481484319000065

I took this to mean that you were going to test it.

**Comment by Ebag333** [comment]
So there were definitely commits that I either never committed or committed locally but never synched.  At least I'm _guessing_ that's what happened, I know that some of these issues I solved before, and I see specific ones that would have failed with a simple test (even in Windows, no need for Mac/Linux) that I know were working before.

Anyway, doesn't matter.

For the issue with:
```
    certName = "cacert.pem"
    os.environ["REQUESTS_CA_BUNDLE"] = getPyfaPath(certName)
    os.environ["SSL_CERT_FILE"] = getPyfaPath(certName)
```

`os.environ` chokes if you try and shove something into it like paths straight up decoded from `windows-1252`.  I don't remember how I solved that before (if I had to guess, probably either using `str(` or `unicode(`), but from a quick search it seems it's a known problem and most people handle it by using `os.environ["REQUESTS_CA_BUNDLE"] = getPyfaPath(certName).encode('utf8')` to put it into a format it handles.

Other things choke if you pass it `utf8` (like anything that uses `os.path`), so we can't just convert it _all_ to `utf8`...that'd be too easy.

@blitzmann I probably stepped on what you did figuring this out, so for that I apologize.  I cleaned up all references to `os.path.join` so they shouldn't exist in the codebase anymore (_except_ in the case of `eos\config`, which I have not touched as it _seems_ to work fine as is, and I wasn't sure if you wanted to point that at the root `config` or not).  

It actually did give me a chance to clean up a few paths that don't point to the standard locations, where we'd done the same fix but outside of `config`.  Now they use the function from `config` so we don't have the same checks scattered through the code base.

I did change the function name as `_getPath` was used twice, and `getPath` is too close to many other things.  If you prefer something other than `parsePath` feel free to change it, just make sure you get the files outside of `config` that point to it.

I think I hit all of the locations where we're getting paths, definitely did for anything use `os.path.join`.  As of right now it's working fine for the test of `Téléchargements`, but I haven't tested it for Mac or Linux.

**Pull request closed without merging**
