### PR TITLE
Issue #1273 Add prereq skills when granting missing skills

### PR DESCRIPTION
**Pull request by burnsypet**
Changes to characterSelection.py:
Remove logic for deciding what skills to add from grantMissingSkills
into a new method generateMissingSkillsMap which functions similarly
to _buildSkillsTooltipCondensed and constructs a complete list of
skills including prereqs.
grantMissingSkills then iterates through this list and applies them
to the character.

---

#1273 

Moved the logic around in characterSelection.py and generating the missing skills map is now done for a new method. The list of missing skills will now include all the prerequisite skills if there are any. The only thing I am concerned about is that if a large list of skills are generated it can take quite a while to apply them to a new character. Applying 15 skills to a new blank all 0 character locked the application up for just about 4 seconds, can understand if you don't want to accept this fix if locking for this long is not desirable behavior.

I have built and tested this fix on Windows 7 but don't have access to test on any other platforms.

### CODE REVIEW

**Comment by pcd1193182** [comment]
This may be a silly question, but why aren't we using the map that's already been built for the tooltip? Or at least reusing the code to generate it? Your new function appears to be almost line-for-line identical to _buildSkillsTooltipCondensed.

**Comment by burnsypet** [comment]
@pcd1193182 _buildSkillsTooptipCondensed builds a skillsMap which contains the skill name and level, but sChar.changeLevel() which is used to change the characters level appears to require a skill id. 

A possible solution to avoid duplicating this code would be to use the existing skillsMap and interate through it generating a new array of levels and ids as part of grantMissingSkills(), however I don't really know enough about how Pyfa works to say if there is a common function for getting the skill id based on it's name.

**Comment by blitzmann** [comment]
@burnsypet thanks for the contribution, however as stated in the issue, this should already be a thing if the user has the option set. It's if very inefficient, as you've noticed; I would like to clean it up at some point and devise a way to make it quicker, but for now it's what we have (see https://github.com/pyfa-org/Pyfa/blob/73dfa25ef063807a5df22dc0c06ccf88b691d7cd/eos/saveddata/character.py#L361 for the code on this). I would be open to hearing thoughts on how it can be improved upon, but for now it is what it is. I'll be closing this issue since functionality already existed - can reconsider as new data / conversations merits. :)

**Comment by burnsypet** [comment]
That's no problem I wasn't aware this was a feature already.

**Pull request closed without merging**
