### PR TITLE
Regarding #2045: automatically create a character for a new sso character 

### PR DESCRIPTION
**Pull request by soro**
and add button to retrieve all chars directly linked to existing sso characters.

I just ran into this issue today and was annoyed enough to just fix it. Let me know if you see any issues with this patch.

### CODE REVIEW

**Comment by DarkFenX** [comment]
I welcome this change. Thanks, will check it tomorrow before merging.

**Comment by DarkFenX** [comment]
@soro i checked it and it looks fine. However, what do you think about scenario when there is a character with the same name as the character being added? Should it update existing character or add a new one?

Currently, it adds a duplicate. At first glance i think updating existing character would make more sense. But, maybe there are some scenarios where this is an undesirable behavior I couldn't think of.

If you have no time - let me know, I can merge and fix it myself.

**Comment by soro** [comment]
Yeah I don't really have time to make the change for a variety of reasons, sorry.

**Comment by DarkFenX** [comment]
It should happen if you remove SSO credentials in pyfa and it again later. But okay, I will handle that. Thanks for the PR.

**Pull request merged**
