### PR TITLE
Mining Yield "per hour". 

### PR DESCRIPTION
**Pull request by IndictionEve**
A little improvement for our mining guys.
Miners usually calculate their mining yield per hour.

### CODE REVIEW

**Comment by Ebag333** [comment]
It's a reasonable change....except for two minor things. 

One, we have always done everything in "per seconds" so people are used to it, and SOME people hate change. 

Two, we don't handle it very well right now because we don't show what it looks like with crystals. So that's a larger issue. 

Ideally we should show it all, but gui space is an issue...

**Comment by IndictionEve** [comment]
Thanks for your comment.
I made the change because I tried some mining fittings and the yield values meant nothing to me. After I multiplied the values i had a idea how "good" the yield really is.
1) "per second"  is simply not a useful (too small) scale for mining yield. Because of this, EFT calculates the yield in minutes. o.smium in hours.
It is no question, that for all other attributes "per seconds" are a great scale to compare.
2) I agree, mining crystals are a totally different topic where all tools i know have no proper solution for this.

**Comment by Ebag333** [comment]
I agree that per hour stats are vastly more useful.  I think we should tie it into #771 and handle both at the same time.

The mining info pane is:
A) Hidden (which is awful UI)
B) Very limited info
C) Shows incorrect statistics (in the case of crystals)

It really needs a full rework.

We can use part of the functionality from #690 to split it out on it's own pane and let users turn it off if they don't want to see it.  Then we can show a lot more info, more accurate info, and a lot more info.

**Comment by blitzmann** [comment]
I agree I like /hr better than /sec, seems more useful. I don't see anything wrong with bringing this change in immediately despite all the other issues the mining pane faces (and crystal calculations, which I still need to look at).

I'll take a look at this hopefully before the next release. :)

**Comment by resinneublem** [comment]
Linking https://www.reddit.com/r/Eve/comments/5o2npc/miner_qol_improvement_m3s_calculated_inclient_on/ where people disagree that m3/h is useful.

Now that EVE has m3/s, it probably makes sense to revert this and stick with what EVE represents.

**Pull request merged**
