### PR TITLE
Requirements for Pyfa

### PR DESCRIPTION
**Pull request by Ebag333**
Caught most of the main ones, I think.
(Yes I'm sneaking EVE-Gnosis in here, just so I don't have a conflict when I submit the cap/shield sim fix)

### CODE REVIEW

**Comment by resinneublem** [comment]
Oh nice. I'd dig something like this too!

**Comment by blitzmann** [comment]
This will be tied in when #812 gets merged

**Comment by Ebag333** [comment]
This should be able to be merged before 812 because we don't reference the `requirements.txt` anywhere in `setup.py`.  Only IDEs like pyCharm will pick it up and warn you about missing prereqs.

(At least, in a normal build scenario.  For Pyfa's weird build this may not hold true.)

**Comment by Ebag333** [comment]
@blitzmann removed EVE-Gnosis as that's going to have to have other PRs merged, so not quite as quick as I'd hoped....

**Comment by blitzmann** [comment]
What is requirements_test?

**Comment by Ebag333** [comment]
>Add requirements for getting this to work on Travis-Ci

Basically if you are running tests against it outside of an IDE that will handle it for you (like pyCharm).

**Pull request merged**
