### PR TITLE
Add Travis Icon

### PR DESCRIPTION
**Pull request by Ebag333**
We worked hard for it. :)

@blitzmann this is ready to be merged.

### CODE REVIEW

**Comment by blitzmann** [comment]
It points to the wrong place

**Comment by Ebag333** [comment]
Why yes it does. :(

Do we want to have an icon for both master and dev?

**Comment by blitzmann** [comment]
No, master only

**Comment by Ebag333** [comment]
Okay. right now master is failing, but as soon as you merge dev down should show passed.

**Comment by blitzmann** [comment]
Sorry, I think you misunderstand. I mean that it's pointing to your repo... not that the branch is incorrect.

**Comment by Ebag333** [comment]
Oh, no, I understood. I just forgot to push the commit.. :)

**Comment by blitzmann** [comment]
oh wait, I see it's fixed... weird

GitHub caching? v-v

**Comment by Ebag333** [comment]
Github just injecting it when it was committed.  I just forgot to hit `push`.

Still getting used to using pyCharm instead of Github's desktop app.

**Pull request merged**
