### PR TITLE
Limit lanaguage from multi to en-us

### PR DESCRIPTION
**Pull request by Ebag333**
Lets this run in 32 bit python.

### CODE REVIEW

**Comment by blitzmann** [comment]
1) Seems there's other commits in this that shouldn't be in there. Plz fix :)
2) I'm okay with this in general for now. There are other changes that need to be made though, I think in the json2sql script.

**Comment by Ebag333** [comment]
Ugh, no idea how that got in there. 

These changes were all that was needed to make a build work without error.

**Comment by Ebag333** [comment]
>1) Seems there's other commits in this that shouldn't be in there (new cap stuff). Plz fix :)

Fixed.

**Comment by blitzmann** [comment]
> These changes were all that was needed to make a build work without error.

Could have sworn this was going to break it https://github.com/pyfa-org/Pyfa/blob/master/scripts/jsonToSql.py#L68

But you're right, it does work. :D

**Pull request merged**
