### PR TITLE
Patch 1105543

### PR DESCRIPTION
**Pull request by Ebag333**
Update DB.  Find changes here:
https://gist.github.com/Ebag333/32221b0adb06cc11e224b73830aacc66

Add effect for defender missile launchers (add 50% RoF bonus on command dessies).

Also fixed the effect for `Fighter Support Unit`.  CCP changed it from a percent to a multiple when they fixed the issue where it made the shield tank worse instead of better.
```
[*] Hermes Compact Fighter Support Unit
  [*] fighterBonusROFPercent: -5.5 => 0.945
  [*] fighterBonusShieldCapacityPercent: 5.5 => 1.055
  [*] fighterBonusShieldRechargePercent: 5.5 => 0.945
  [*] fighterBonusVelocityPercent: 5.5 => 1.055
```

One thing left to investigate (though nothing preventing this from being merged).  I _believe_ that there's an effect on the defender skill to increase range.  That hasn't been implemented yet.

Speaking of range, range is broken on the defender missiles because of the formula we use.  Defender missiles have agility of 0, so just had to allow that to pass into the calcs (use or instead of and, since python counts `agility = 0` the same as `agility = False`).

### CODE REVIEW

**Comment by Ebag333** [comment]
>One thing left to investigate (though nothing preventing this from being merged). I believe that there's an effect on the defender skill to increase range. That hasn't been implemented yet.

And that's done.

@blitzmann, merge plxkthx!

**Comment by Ebag333** [comment]
`blitzmann changed the base branch to pyfa-org:singularity from pyfa-org:master 23 minutes ago`

Did you mean to point this at the dev branch?

Hmm, interesting that all these commits are now showing.

**Comment by blitzmann** [comment]
I meant to point it at sisi branch, because this is dealing with a sisi update.

All the commits are showing up because the sisi branch isn't updated to master yet

**Comment by Ebag333** [comment]
This isn't a SiSi update. This is live on TQ.

**Comment by blitzmann** [comment]
oh shit, really? I thought this was something coming next teusday for some reason. Will check it out and merge soon

**Comment by Ebag333** [comment]
I'm just on the ball with updates. :D 

It's actually coincidental that I even really worked on it.  I was curious about DB changes, because there's Christmas gifts in there, so started poking around the change log...one thing led to another....

**Comment by blitzmann** [comment]
looks good, thanks. Will make a release tomorrow barring any major bugs reported :)

**Pull request merged**
