### PR TITLE
Price optimize

### PR DESCRIPTION
**Pull request by DarkFenX**
See ticket #1841 for idea overview. Not ready to be merged yet, still work to be done. Creating to keep changelog:

- [x] price column for fighters tab
- [x] attempt to fetch price globally if Jita has no data on specified item
- [x] fix sorting in "compare" tab for price column
- [x] implement multibuy export price optimization main functionality
- [x] show that multibuy export price optimization is in progress (by graying out modal window)
- [x] fix bug with fit export window checkbox sizers
- [x] implement in-place price optimization main functionality
- [x] integrate in-place price optimization with undo/redo
- [x] block fit changes while in-place price optimization is in progress
- [x] decide how to invoke in-place price optimization

### CODE REVIEW

**Comment by DarkFenX** [comment]
Added all needed backend changes and enabled price optimization for multibuy export.

**Comment by DarkFenX** [comment]
What works:

- optimization by price in-place
- optimization by price for multibuy export

What still needs to be done:

- multibuy export price optimization: way to show that export is underway (in case network fetches take some time we should gray out export window or something, for now it will just wait until everything is done and close)
- in-place price optimization: way to show that it is in progress (block fit modification while prices are being fetched and fit is being modified)
- decide where to put in-place price optimization invocation (ATM i've added it to edit > optimize price, but this is mostly for testing needs) - would welcome some help on this. I cannot find good location for it.
- integrate in-place price optimization with undo/redo
- in fit export dialog, there is still bug which forces all checkbox blocks to have height of the biggest checkbox block. So if you have 2 blocks of checkboxes - 4 and 1, block with 1 checkboxes will take as much vertical space as 4. Previously it was masked by the fact that EFT export and multibuy export had 3 checkboxes, now multibuy has 4 (and i'd like to add one to ESI - "loaded charges").

On a side-note, while implementing this feature i had to drop idea of replacing items with "better" and cheaper alternative just because finding better item is not a trivial task and is huge maintenance burden due to inconsistencies in CCP data. Consider few examples:

-  durationBonus/durationSkillBonus: high duration on resist mods and prop mods is good while low duration is good for reps. So, there's no way to say if increase in duration is good without knowing context, highIsGood property is meaningless.
- speedFactor: high is good for ABs/MWDs, high is bad for webs.
- aoeCloudSizeBonus: high is good for GDs, high is bad for rigors/crash
- signatureRadiusBonus: high is good for TPs, high is bad for MWDs/x-instinct.

There were many more examples, but you get the gist. Moreover, highIsGood value is fucked up for quite many attributes which have no similar conflicts. By the time i found too many unsolvable inconsistencies (as listed above) I've added ~30 highIsGood overrides to db generation script to fix various hardwirings, modules and drugs (most of these were negative bonuses like -3% cycle time with highIsGood = 1)

So, now we just seek for items which are "the same" - like CN/DG invulns.

**Comment by blitzmann** [comment]
@DarkFenX I added a wait dialog to halt GUI until the callback is called. Let me know if it works for you (seems to work for me on Windows :) )

**Comment by DarkFenX** [comment]
Thanks! It works well.

**Comment by DarkFenX** [comment]
Actually I tested it more thoroughly:

1) alignment of notification window is alright on xorg, but is not on wayland:
modal
2) This window does not prevent fit changes while fetch is in progress. This is not ideal but might be acceptable (introduces risk of various race conditions, but at least user has been warned).
3) It seems to be implemented as separate window, which is visible on alt-tab menu

**Comment by DarkFenX** [comment]
Added window disabler. Now we have to implement UI blocking for multibuy optimization and probably can merge.

Context menu changes can be done outside of scope of this pull request.

**Pull request merged**
