### PR TITLE
Implemented copying the currently open fit stats to the clipboard.

### PR DESCRIPTION
**Pull request by m-sasha**
Added a menu item in the "Edit" menu, which copies a compact form of the currently selected fit stats to the clipboard.

### CODE REVIEW

**Comment by IndictionEve** [comment]
would love to see this in pyfa for base stats.
can be enhanced step by step if needed.

**Comment by Gochim** [comment]
Hi

Is this pull request worth looking into to solve it's issues and make it into master? Or there are some serious problems that I'm not seeing with that PR so that it's not worth bothering?

I there is nothing serious with it - I could pretty it up and finish...

**Comment by DarkFenX** [comment]
@Gochim this pull request was submitted during my absence so I haven't really checked it. No idea why @blitzmann ended up not accepting it. But i can see following things which have to be done before accepting it:

1) Stat format has to be discussed and agreed on
2) Export could be moved to regular ctrl-c menu (where EFT, multibuy and other exports are)

**Comment by DarkFenX** [comment]
@Gochim please create a ticket for discussion of format. I think it's more appropriate than doing it in here.

**Pull request merged**
