### PR TITLE
Updated ECM to be more descriptive

### PR DESCRIPTION
**Pull request by Ebag333**
Gave it the RAH treatment. Now shows min/max values if it's a racial (since they have a strong/weak value), and only one for multi/burst (since it's omni).  Tooltip shows all four broken out.

Tried showing all 4 in the misc window, it gets kinda cluttered.  Showing min/max with all four broken out in the tooltip seems to be the best compromise.

### CODE REVIEW

**Comment by Ebag333** [comment]
Example of the selected racial ECM:
http://puu.sh/pqyGm/5aba0dd6b6.png

**Comment by blitzmann** [comment]
Capitalize the sensor types and it's good to go =)

**Comment by Ebag333** [comment]
Done and done.

**Comment by blitzmann** [comment]
Thanks!

**Pull request merged**
