### PR TITLE
Fix wxWidget crash caused by GDI object limit

### PR DESCRIPTION
**Pull request by cryonox**
This closes 

https://github.com/pyfa-org/Pyfa/issues/2121
https://github.com/pyfa-org/Pyfa/issues/2261
https://github.com/pyfa-org/Pyfa/issues/2225

### CODE REVIEW

**Comment by DarkFenX** [comment]
Sorry for missing the pull request. Was busy with AT and kids. Will look into it later this week

**Comment by cryonox** [comment]
Ya it was used to check "memory leak" from gc and to know the current gdi object count so that I know if it's about to crash or not. I thought it might be useful in case this kind of thing happen again since I am pretty sure shipbrowser is not the only place this is happening. it's just the worst case of it.

**Comment by DarkFenX** [comment]
Thx, i wish i had enough experience to debug similar crashes on linux/mac

**Comment by cryonox** [comment]
Did you forgot to merge? @DarkFenX

**Comment by DarkFenX** [comment]
Oh wtf

**Comment by DarkFenX** [comment]
Sorry about that

**Pull request merged**
