### PR TITLE
Multilanguage

### PR DESCRIPTION
**Pull request by HaoxuanGuo**
This is a simple edition for multilanguage.
**Multilingual features may reduce some performance**
I added language packs in the pyfa. Of course, only some simple translate. I have to admit that this function is a huge work. I will do it little by little until all the part can be translate by an extra language pack. 
Up to now, I only translated some UI. Because of the huge work, I decide to merge it when I did a part to escape some unexpected problems.
So, this is the first part. I will do it little by little.

### CODE REVIEW

**Comment by blitzmann** [comment]
@icyskyair 

Neato, thanks for this initial work!

However, I wish to stress that localization is going to be a huge project (as I'm sure you're aware). I want to know more about it before we make a huge effort for it.

### UI Localization

I do have a suggestion. Instead of rolling your own translation database, where you have a `from` and `to` column, and then writing functions that fetch that, I would recommend that you instead use the packages that python itself gives you, which is standardized:

https://docs.python.org/3/library/i18n.html

It's nearly the same thing that you're doing, however instead of a sqlite database, it runs on flat files. Additionally, this is a standard for software development, so I would much prefer this route.

The way that it works is that you provide language packs that's basically a key value pair. For example:

English:"
```"additional_panel_projected": "Projected"
"additional_panel_command": "Command"```

Simplified Chinese:
```"additional_panel_projected":	"预计"
"additional_panel_command": "指挥"```

And to call it in python;

`_('additional_panel_projected')`

Pretty simple. It's just an example, so I'm not too sure on the proper syntax (I'm sure the actual language pack file is different). But this is the standard way of doing localization for the UI.

### EVE data localization
The EVE Data is probably not going to be handled by the python localization. I don't quite know what I'm going to do about it, I first need to run some benchmarks and see just how much extra data having multiple languages would incur, and if it's too great, devise a way to support a plug-able system maybe? not sure, but this is going to take much more time and research to get right

**Comment by blitzmann** [comment]
In fact, I remember there was some guy that was trying to localize the UI...

Yep! https://github.com/liuyuran/Pyfa

Note how his localization files are under a structure like `locale/en_US/LC_MESSAGES/`. And here's the mapping for it: https://github.com/liuyuran/Pyfa/blob/master/locale/en_US/LC_MESSAGES/lang.po.

There's also a `lang.mo`. i'm not exactly sure what that is, maybe a compiled version?

This is utilizing the i18n standard for localization, and is the direction we should take. You can look at how that repo gets it set up if needed

Looks like that repo went dead a while ago though, no updates since Aug 2016. So do keep in mind it's using older code, python 2.7. I can load it on my machine, but not sure if you have the dependencies.

@liuyuran you still around?

**Comment by icyskyair** [comment]
@blitzmann Okay, I will have to try.

**Comment by blitzmann** [comment]
Closing in favor of recent discussions and work surrounding localization, see #1545, 2198

**Pull request closed without merging**
