### PR TITLE
Fix for #1061

### PR DESCRIPTION
**Pull request by blitzmann**
Simple fix

### CODE REVIEW

**Comment by blitzmann** [comment]
@Ebag333 I don't know what I'm doing ;_;

Travis says test failed in `tests/test_modules/test_service/test_fit.py` due to error importing wx, I commented out the wx stuff (you stated in the test PR that I merged it in overlooking a test that was failing due to this), but it still doesn't work??

< confused

**Comment by Ebag333** [comment]
>@Ebag333 I don't know what I'm doing ;_;

Welcome to the club. :)

>Travis says test failed in tests/test_modules/test_service/test_fit.py due to error importing wx, I commented out the wx stuff (you stated in the test PR that I merged it in overlooking a test that was failing due to this), but it still doesn't work??

I have no idea where it's getting wx from. I can't find an import statement for wx anywhere in there.  It _was_ working at one point, but I might be just thinking of my local test.

Can you see where it might be calling it from?

**Comment by blitzmann** [comment]
> Can you see where it might be calling it from?

As I said, I commented out all reference to wx in that file. Gonna try to comment the whole file and see what happens. It's compounded by the fact that I can seem to get any of the tests to run correctly on my local machine either ¯\_(ツ)_/¯

**Comment by Ebag333** [comment]
The reference to wx in that file was an attempt to override any imports and not let it actually import wx. (Most recent commit) 

Unless you found another wx import statement?

**Comment by blitzmann** [comment]
> Unless you found another wx import statement?

The only "wx" found under the `tests/` path was what I commented out. Again, don't know any of these things, just gonna play around with it until it works.

**Comment by blitzmann** [comment]
hey that works lol

Maybe it was importing something that also import wx... but I couldn't see where.

**Pull request merged**
