### PR TITLE
Updates to Abyss room-wide and localized weather effects

### PR DESCRIPTION
**Pull request by fonsuiplaysvideogames**
Addressing #1880 :
1) Added relevant room-wide and localized effects to drones
2) Removed stacking penalties from room-wide and localized effects
3) Removed erroneous comments

@DarkFenX Please let me know if there are any issues with this code so that I can fix it up if necessary. Thanks!

### CODE REVIEW

**Comment by fonsuiplaysvideogames** [comment]
@DarkFenX @blitzmann 

Can you guys let me know if this code needs changes in order to be merged in?

**Comment by DarkFenX** [comment]
We're somewhat inactive. I believe blitzz went back to inactivity and i have IRL pressure, so cannot keep up with pyfa development needs. I will check your PR now.

**Comment by DarkFenX** [comment]
@fonsuiplaysvideogames why did you remove stacking penalties from multiple abyssal cloud effects? Are you confident they are not stacking penalized?

**Comment by fonsuiplaysvideogames** [comment]
I am uncertain of the specific rules you're describing, but what I do know is that the observed value in-game matched the value in pyfa when I had the stacking penalties removed, and when the stacking penalties were in I got inconsistent values.

**Comment by DarkFenX** [comment]
@fonsuiplaysvideogames could you give some specific example? Full fit, projected effects/environment, just so I could confirm it myself before merging

**Comment by fonsuiplaysvideogames** [comment]
Nothing sensitive, just a testing fit I was using on Singularity. Two Drone Scope Chip II rigs, an Omnidirectional Tracking Enhancer, and a range scripted Omnidirectional Tracking Link on a bare ship was generating different results in-game in a Dark Abyss site and in pyfa.

**Comment by DarkFenX** [comment]
If you were looking at drone optimal range - negative and positive modifications are stacking penalized separately. Everything you listed is a positive modification, and optimal range penalty from darks is negative modifications, so at least in theory removing stacking penalty flag should not affect final number.

**Comment by blitzmann** [comment]
I'm around, but focusing what little free time I have on trying to figure out i18n stuff. 

@DarkFenX you seem to be much more in the know with what's going on with this, so I'm going to defer to you unless you need some assistance with it.

**Comment by fonsuiplaysvideogames** [comment]
If I wanted to change this to add the effects to drones without changing the stacking penalty code, what would be the best way to go about thatit?

**Comment by DarkFenX** [comment]
@fonsuiplaysvideogames looks good with the changes. As for the stacking penalty issue - please create separate ticket with some concrete data to work on, this way we will be able to figure out what would be a way to fix it properly.

**Pull request merged**
