### PR TITLE
Re-written in much greater detail instructions how to set up the project

### PR DESCRIPTION
**Pull request by Gochim**
It wasn't very clear how to set up project when I decided to contribute myself, so decided as a first task to create clear and simple guide. 

- Written instructions how to set up the project in CLI.
- Added new guide to set project up using PyCharm/IntelliJ. 
- Since it took too much space - separated in into separate file *contributing.md*.

### CODE REVIEW

**Comment by DarkFenX** [comment]
Thanks for writing it!

**Comment by DarkFenX** [comment]
Actually I wonder if having it on wiki would be more reasonable, and just linking it from readme?

@Gochim, could you check [the wiki](https://github.com/pyfa-org/Pyfa/wiki) please and tell what you think?

**Comment by Gochim** [comment]
Well it's definitely a bit old. It seems to me that usually people look at readme.md or contributing.md first, so they should stay where they are. And copy/pasting it into wiki is not a good way either. So, if you don't mind, I'll simply add a link to contributing.md into the wiki page - so we'll keep one source of information.

**Comment by DarkFenX** [comment]
I do not. In fact, I've asked exactly because I have no idea where people look first. Did not know that contributing.md was a standard.

**Comment by Gochim** [comment]
Well, my Udacity course at least said so :) 

And... done.

**Pull request merged**
