### PR TITLE
Centralize HighIsGood overrides

### PR DESCRIPTION
**Pull request by blitzmann**
This iterates on #1876 and centralizes the overrides into EOS proper. This allows highIsGood attribute to be calculated corrected for all cases, not just the mutations page

### CODE REVIEW

**Comment by DarkFenX** [comment]
I think that this implementation has its downsides, at least in theory. As far as I know highIsGood participates in attribute calculation (picking best value for preAssignments and postAssignments), and CCP will definitely use their own "wrong" value for that. While there're no such calculations affected by that now, they might appear in future.

So to be safe i'd leave highIsGood as-is, and would add highIsGoodDisplay which will work as you implemented, and which should be used for display purposes.

**Comment by blitzmann** [comment]
That is a very good point, did not consider that. Will take a look at adding new property of `highIsGoodDisplay` :)

Thanks!

**Comment by DarkFenX** [comment]
FYI your changes do not work for me. Both before my commits and after them.
```
pyfa v2.7.5
EVE Data Version: 1459933 (2019-02-16 13:18:51)

OS version: Linux-4.19.0-2-amd64-x86_64-with-debian-buster-sid
Python version: 3.7.2+ (default, Feb 27 2019, 15:41:59) 
[GCC 8.2.0]
wxPython version: 4.0.4 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.18
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.7.3

####################

Traceback (most recent call last):
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinViews/fittingView.py", line 88, in fitSelected
    view.fitSelected(event)
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinViews/fittingView.py", line 344, in fitSelected
    self.slotsChanged()
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinViews/fittingView.py", line 525, in slotsChanged
    self.generateMods()
  File "/home/dfx/Workspace/eve/pyfa/gui/builtinViews/fittingView.py", line 476, in generateMods
    fit = sFit.getFit(self.activeFitID)
  File "/home/dfx/Workspace/eve/pyfa/service/fit.py", line 310, in getFit
    self.recalc(fit)
  File "/home/dfx/Workspace/eve/pyfa/service/fit.py", line 595, in recalc
    fit.clear()
  File "/home/dfx/Workspace/eve/pyfa/eos/saveddata/fit.py", line 440, in clear
    self.modules,
  File "/home/dfx/Workspace/eve/pyfa/eos/saveddata/fit.py", line 229, in modules
    return self.__modules
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/attributes.py", line 275, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/attributes.py", line 674, in get
    value = self.callable_(state, passive)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/strategies.py", line 708, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/strategies.py", line 850, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/baked.py", line 477, in all
    return list(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/loading.py", line 578, in _instance
    state.manager.dispatch.load(state, context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/event/attr.py", line 297, in __call__
    fn(*args, **kw)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/mapper.py", line 3291, in _event_on_load
    instrumenting_mapper._reconstructor(state.obj())
  File "/home/dfx/Workspace/eve/pyfa/eos/saveddata/module.py", line 127, in init
    self.build()
  File "/home/dfx/Workspace/eve/pyfa/eos/saveddata/module.py", line 155, in build
    attr = self.item.attributes[x.name]
KeyError: 'power'
```
This happens when I load a fit with 2 medium abyssal cap batteries.

**Comment by DarkFenX** [comment]
don't think it's needed

**Pull request closed without merging**
