### PR TITLE
anaconda setup + wxpython changes

### PR DESCRIPTION
**Pull request by tadeasf**
Anaconda environment setup which creates working package on m1 macs. This is my first public pull request, if I need to change anything or I did anything wrong, please, let me know, I'll gladly change it. Did my best to help solve these issues:

https://github.com/pyfa-org/Pyfa/issues/2534
https://github.com/pyfa-org/Pyfa/issues/2533
https://github.com/pyfa-org/Pyfa/issues/2528

One thing that I do not understand is that it seems to slow down the environment significantly in comparison to earlier versions (latest working version on m1 macs sonoma 14 is 2.29.x as far as I found. It seems to have siginifcantly speedier GUI.

### CODE REVIEW

**Comment by tadeasf** [comment]
I tested it again and it seems to speed up from 2.54.0 -> 2.54.1. Thus this version looks good.
Package here: https://drive.google.com/drive/folders/1x1-SjQD_pR7R05j2yQg5T3kIAU6UQL-w?usp=drive_link

**Comment by m-sasha** [comment]
I'm not a maintainer, but I doubt the unnecessary formatting changes will be welcome. The removal of copyright notices from files - even less so.

**Comment by tadeasf** [comment]
> I'm not a maintainer, but I doubt the unnecessary formatting changes will be welcome. The removal of copyright notices from files - even less so.

thank you! i have not paid attention to the copyright notices, it was not my intention to violate them like that. I hear you and now that I have a look at the pull request again I see how messy it is. I will have a look at it again and implement strictly necessary changes only. Cheers!

**Comment by fruitchewy** [comment]
deleted copyrights aside, this seems to also just not work on several levels
- conda env name in yml doesn't match references in scripts
- hardcoded conda paths
- no pyinstaller in environment.yml
- no matplotlib in environment.yml
- still getting wx crashes when built with 4.1.1

**Comment by DarkFenX** [comment]
We had a branch with updated dependencies, `dep_facelift`, for a while. It included updated wx too, but was broken for a while due to issues on wx side (it mostly broke on windows).

I will pick specific changes from your pull request manually later.

**Comment by DarkFenX** [comment]
I looked through all the changes.

I don't mind formatting changes and some header removal that much by itself. But I can't tell apart changes to logic from changes to formatting.

I tried to be careful but I do not see anything I can extract from this pull request. Some changes (like to spec files) make wrong assumptions about build process (which is described in .appveyor.yml file). I'd agree they need some cleanup, but it's not that.

Closing it, if you think there is anything valuable to be transferred (in context of fixed mac builds, see latest pre-release), please poke me.

**Pull request closed without merging**
