### PR TITLE
add market source ceve-market

### PR DESCRIPTION
**Pull request by copyliu**

### CODE REVIEW

**Comment by blitzmann** [comment]
Thanks! Will take a look tonight, but the code seems reasonable.

We've noticed an influx of Chinese interest in pyfa in the last few months (to the point where we're currently developing localizations). Did something happen with Serenity that has generated more playtime?

**Comment by copyliu** [comment]
because Serenity was finally re-opened and synced up to TQ's version

**Comment by blitzmann** [comment]
Oh, I had no idea that serenity shut down for a time. Thanks for the info, was just curious :)

**Comment by DarkFenX** [comment]
FYI i split market sources in 2 groups and added code to process those groups, to avoid cross-fetches, in 63632e09b333e05047f0682858282f537cb9a5cb

**Pull request merged**
